opensupplyhub/open-supply-hub

.github/workflows/deploy_to_aws.yml

Add `deploy-plan-only` as input in GitHub flow and relevant logic
This needs to have a safe option to -"dry-run" deployment to environment.

Add option to run terraform plan only

---

doc/release/RELEASE-NOTES.md
src/django/api/serializers/facility/facility_index_details_serializer.py
src/django/api/serializers/facility/facility_index_extended_field_list_serializer.py
src/django/api/serializers/facility/facility_index_serializer.py
src/django/api/serializers/facility/utils.py
src/django/api/tests/test_sector_api.py
src/django/api/views/facility/facilities_view_set.py

[OSDEV-728](https://opensupplyhub.atlassian.net/browse/OSDEV-728) API. Sector values are missing from GET /facilities response.
- Added 'sector' data response to endpoint **api/facilities/** similar as we got in **api/facilities/{id}**.
- Excluded _'sector'_ field if parameter _'detail'_ not set or equal _'true'_
- Updated docs for Swagger.

[OSDEV-728] API. Sector values are missing from GET /facilities response. 

---

src/django/api/serializers/user_api_info_serializer.py
src/django/api/tests/test_api_limit.py

**Fix Django api limit tests that was sensitive to date**
- Fixed api limit tests for specific day 29-31
- Fixed calculation of current usage in the situation of contributor start paid subs between day 29-31

Fix Django api limit tests that was sensitive to date

---

doc/release/RELEASE-NOTES.md
src/kafka-tools/Dockerfile

Kafka tool 3.5.1 isn't available anymore, so version is upgraded to 3.5.2.
[OSDEV-915](https://opensupplyhub.atlassian.net/browse/OSDEV-915)

[OSDEV-915] Upgrade Kafka tool version to 3.5.2

---

src/kafka-tools/Dockerfile

Use correct path to Kafka with version 3.5.2
[OSDEV-915](https://opensupplyhub.atlassian.net/browse/OSDEV-915)

Fix Kafka  docker to use correct path

---

doc/release/RELEASE-NOTES.md
src/django/api/tests/test_facility_list_view.py
src/django/api/views/facility/facility_list_view_set.py

[OSDEV-918](https://opensupplyhub.atlassian.net/browse/OSDEV-918) ContriBot. New lists are not populating in Monday board and are not sent to slack
- Added validation error if description contain "|"

[OSDEV-918] ContriBot. New lists are not populating in Monday board and are not sent to slack

---

doc/release/RELEASE-NOTES.md
src/django/api/tests/test_facility_delete.py
src/django/api/views/facility/facilities_view_set.py

[OSDEV-644](https://opensupplyhub.atlassian.net/browse/OSDEV-644) Error when trying to delete a facility with only one contributor
- Implemented logic to ensure that when we delete a facility, we also clear the corresponding data in the api_facilityclaimreviewnote table.
- Added tests

[OSDEV-644] Error when trying to delete a facility with only one contributor

---

deployment/environments/terraform-test.tfvars

Increase the resources for the DedupeHub on the Test environment to 4 CPU and 8GB.
- Update `app_dd_fargate_cpu`, `app_dd_fargate_memory`, and `app_dd_ecs_desired_count`.

Increase the resources for the DedupeHub on the Test environment to 4 CPU and 8GB.

---

deployment/environments/terraform-production.tfvars

During deploy to production it's turned out that terraform configuration is mislead. This pr restores original configuration.

[OSDEV-952] Restore correct prod configuration

---

doc/release/RELEASE-NOTES.md
src/django/api/serializers/facility/facility_index_details_serializer.py
src/django/api/serializers/facility/utils.py
src/django/api/tests/test_facility_index_details_serializer.py

[OSDEV-888](https://opensupplyhub.atlassian.net/browse/OSDEV-888): Fix an error that occurs when trying to open a facility from the Status Reports page
The error occurred due to activity reports with the status `pending` containing fields with `null` values and these values pass to the `format_date` function as an argument.
Modified the `get_activity_reports` method in the `FacilityIndexDetailsSerializer` to prevent passing a falsy `date` argument into the `format_date` function.

[OSDEV-888] Fix an error that occurs when trying to open a facility from the Status Reports page

---

.github/workflows/destroy.yml
deployment/delete_ecr
doc/release/RELEASE-NOTES.md

[OSDEV-857](https://opensupplyhub.atlassian.net/browse/OSDEV-857) [Bug] Pre-prod isn't deleted by the 'terraform destroy' script. 
* Command for destroying ecr repositories on AWS pre-prod has been added.
( Need to add settings to the command for destroying DB Instance to complete the job)

 [OSDEV-857] [Bug] Pre-prod isn't deleted by the 'terraform destroy' script.

---

doc/release/RELEASE-NOTES.md
src/app/src/actions/filters.js

[OSDEV-996](https://opensupplyhub.atlassian.net/browse/OSDEV-996) EM. Fix the default facility sorting order 
* The default sorting order for embedded maps was broken (changed to Descending by # Contributors). The default sorting order for embedded maps has been fixed (changed it back to Ascending by Name).

[OSDEV-996] EM. Fix the default facility sorting order 

---

deployment/environments/terraform-preprod.tfvars
deployment/environments/terraform-production.tfvars
doc/release/RELEASE-NOTES.md

The production environment seems stable enough even with fewer workers/containers than usual. We've been running with 12 for the past two days, so there's no need to spend money on 16. That's why we've decided to decrease the number of containers for the prod and preprod environments to 12.

Decrease the number of containers for prod and preprod environments

---

doc/release/RELEASE-NOTES.md
src/app/src/components/Navbar/InternationalMenu.jsx
src/app/src/components/Navbar/MobileInternationalMenu.jsx

[OSDEV-745](https://opensupplyhub.atlassian.net/browse/OSDEV-745) New "Portuguese" translated resources option is not visible on production website.
- Added Portuguese" translated resources to International menu

[OSDEV-745] New "Portuguese" translated resources option is not visible on production website.

---

deployment/environments/terraform-preprod.tfvars
deployment/environments/terraform-production.tfvars
deployment/environments/terraform-test.tfvars
doc/release/RELEASE-NOTES.md

- 1.12 changes: Resource allocation has been optimized for the Test environment. The number of ECS tasks in the Test environment has been reduced from 4 to 2, while maintaining system stability.
- Back merge of the 1.11 changes: The production environment seems stable enough even with fewer workers/containers than usual. We've been running with 12 for the past two days, so there's no need to spend money on 16. That's why we've decided to decrease the number of containers for the prod and preprod environments to 12.

Decrease the number of containers for prod, preprod and test environments

---

src/dedupe-hub/api/app/main.py

Dedupe Hub Fix: handle condition when no message received on kafka topic
- Those changes with condition fix possible stuck when no message received or DB is empty.

Dedupe Hub Fix: handle condition when no message received on kafka topic

---

doc/release/RELEASE-NOTES.md
src/app/src/__tests__/components/ClaimFacilityDashboardControls.test.js
src/app/src/actions/claimFacilityDashboard.jsx
src/app/src/components/DashboardClaimDetailsControls.jsx
src/app/src/reducers/ClaimFacilityDashboardReducer.jsx
src/app/src/util/util.js
src/django/api/mail.py
src/django/api/templates/mail/claims_team_signature_block.html
src/django/api/templates/mail/claims_team_signature_block.txt
src/django/api/templates/mail/message_claimant_body.html
src/django/api/templates/mail/message_claimant_body.txt
src/django/api/templates/mail/message_claimant_subject.txt
src/django/api/tests/test_facility_claim_view_set.py
src/django/api/views/facility/facility_claim_view_set.py

[OSDEV-997](https://opensupplyhub.atlassian.net/browse/OSDEV-997) - Facility Claims. Send messages to claimant from the claim request page.
A new button, 'Message Claimant' has been added to the update status controls on the Facility Claim Details page. After successfully sending a message, the message text is recorded in the Claim Review Notes.
A new method, `message_claimant`, was added to the `FacilityClaimViewSet` for handling a POST request on the url-path `message-claimant` for messages to the claimant. 
Mail templates for the message to the claimant and the claims team signature were also added.

[OSDEV-997] Facility Claims. Send messages to claimant from the claim request page.

---

deployment/terraform/container_service.tf
deployment/terraform/iam.tf
deployment/terraform/opensearch.tf
doc/release/RELEASE-NOTES.md

Fix https://opensupplyhub.atlassian.net/browse/OSDEV-1001
1. Provision OpenSearch.
2. Apply VPC options that make OpenSearch available at the same subnet as PostgreSQL.
3. Apply security groups for OpenSearch.
4. Prepare bare minimum cluster configs for current setup (2 instances of t3.small.search).
5. Enable advanced security options.
6. Connect all CloudWatch log types to OpenSearch.

[OSDEV-1001] Deploy OpenSearch service to our infrastructure

---

deployment/environments/terraform-staging.tfvars
doc/release/RELEASE-NOTES.md

In response to recent stability observations of the staging environment, resource allocation has been optimized by reducing the number of ECS tasks from 8 to 6 for the Django app instances, thus maintaining system stability.
**Note:** Starting April 23rd, the staging environment has 6 ECS tasks for the Django app instances that are up and running, with no detected outages.

Reduce the number of ECS tasks from 8 to 6 for the staging env

---

deployment/terraform/efs.tf
deployment/terraform/iam.tf

The error that occurred during deployment to the Test environment -> https://github.com/opensupplyhub/open-supply-hub/actions/runs/9076795226/job/24940323859
**Fix:**
Made Logstash and OpenSearch-related resources unique per environment, specifically the IAM role for OpenSearch and the EFS for Logstash.
_Note: I tested the changes for the Development environment -> https://github.com/opensupplyhub/open-supply-hub/actions/runs/9077362009 and for the Test environment -> https://github.com/opensupplyhub/open-supply-hub/actions/runs/9077422395_

Make logstash and opensearch related resources unique per env

---

src/anon-tools/do_restore.sh

* if newer database has changes with new relations/constraints, restoring the database from dumps leads to conflicts. So removing schema allows not to have conflicting data and restoring database from empty state

Delete the 'public' scheme before database restore

---

doc/release/RELEASE-NOTES.md
src/django/api/reports/pending_match_records_for_certain_api_users.sql

[OSDEV-1068](https://opensupplyhub.atlassian.net/browse/OSDEV-1068) Make a static report that lists the number of POTENTIAL_MATCH records for certain API users
Created report that shows the number of records from the `api_facilitymatch` table for contributors: [Textile Exchange](https://opensupplyhub.org/admin/api/contributor/2060/change/), [ZDHC](https://opensupplyhub.org/admin/api/contributor/1045/change/), [Worldly](https://opensupplyhub.org/admin/api/contributor/685/change/), [Amfori](https://opensupplyhub.org/admin/api/contributor/3356/change/)

[OSDEV-1068] Make a static report that lists the number of POTENTIAL_MATCH records for certain API users

---

doc/release/RELEASE-NOTES.md
src/django/api/tests/test_login_to_oar_client.py
src/django/api/views/auth/login_to_oar_client.py

[OSDEV-1019](https://opensupplyhub.atlassian.net/browse/OSDEV-1019) Login page. User did not click confirmation link.
Fixed an error message to 'Your account is not verified. Check your email for a confirmation link.' when a user tries to log in with an uppercase letter in the email address and their account has not been activated through the confirmation link.

[OSDEV-1019] Login page. User did not click confirmation link.

---

doc/release/RELEASE-NOTES.md
src/react/src/__tests__/components/Footer.test.js
src/react/src/util/constants.jsx

[OSDEV-1030](https://opensupplyhub.atlassian.net/browse/OSDEV-1030) Site Header & Footer. Add Blog and Career Links, change order of links on footer.
Replaced the "Donate" button with a "Blog" button in the header and added links to the "Blog" and "Careers" pages in the footer. 
These changes ensure a consistent user experience across both ([map site](http://www.opensupplyhub.org/) and [info site](https://info.opensupplyhub.org/)), making navigation easier and more intuitive for users.

[OSDEV-1030] Site Header & Footer. Add Blog and Career Links, change order of links on footer.

---

src/django/api/management/commands/post_deployment.py

Removed calling `clean_facilitylistitems` command from `post_deployment` command.

Remove calling clean_facilitylistitems command from post_deployment command

---

deployment/terraform/task-definitions/app.json
doc/release/RELEASE-NOTES.md
docker-compose.yml

* update AWS log format so that lines look like this:
`[11/Jun/2024:21:06:48 +0000] 'GET /web/environment.js HTTP/1.1' 200 | 3118ms`

Change format of AWS CloudWatch to not log IP address

---

deployment/run_cli_task
doc/release/RELEASE-NOTES.md

An additional loop was added to the `run_cli_task` script that repeatedly checks the status of an AWS ECS task, waiting for it to stop.
The current solution should prevent the `Waiter TasksStopped failed: Max attempts exceeded` error that occurred during the execution of the `post_deployment` task.

Wait till AWS ECS task ends

---

deployment/terraform/container_service.tf
deployment/terraform/iam.tf
deployment/terraform/opensearch.tf

Fix error while temporal disabling of the OpenSearch:
```
│ Error: Missing resource instance key
│ 
│   on iam.tf line 390, in data "aws_iam_policy_document" "opensearch":
│  390:       aws_opensearch_domain.opensearch.arn
│ 
│ Because aws_opensearch_domain.opensearch has "count" set, its attributes
│ must be accessed on specific instances.
│ 
│ For example, to correlate with indices of a referring resource, use:
│     aws_opensearch_domain.opensearch[count.index]
```
See error message [here](https://github.com/opensupplyhub/open-supply-hub/actions/runs/9594661205/job/26457722475#step:7:170).

[Osdev-1004] fix opensearch count property

---

doc/release/RELEASE-NOTES.md
src/django/api/reports/contributor_type_by_percent.sql

[OSDEV-1098](https://opensupplyhub.atlassian.net/browse/OSDEV-1098) Reporting. A column's values in the report "Contributor type by %" are not cumulative.
The SQL for the report has been rewritten in such a way that first calculates the monthly counts, then computes the cumulative counts for each month, and finally applies the calc_column function to get the desired 
percentages. This gives us the accumulated values for each month.

[OSDEV-1098] Reporting. A columns values in the report "Contributor type by %" are not cumulative.

---

doc/release/RELEASE-NOTES.md
src/dedupe-hub/api/app/utils/constants.py
src/django/oar/settings.py
src/react/public/index.html

[OSDEV-1088](https://opensupplyhub.atlassian.net/browse/OSDEV-1088) Collecting users' public IP addresses in the Rollbar error tracker has been disabled to meet GDPR compliance.

[OSDEV-1088] Disable collecting users' public IP addresses in the Rollbar error tracker

---

src/django/oar/urls.py

The link to the MIT License on the Open Supply Hub API page has been updated.

Update link to the MIT License

---

src/react/src/__tests__/components/DashboardClaimsListTable.test.js
src/react/src/util/util.js

Follow-up patch for [OSDEV-273](https://opensupplyhub.atlassian.net/browse/OSDEV-273) that fixes sorting of lower cased string values.
[OSDEV-273]: https://opensupplyhub.atlassian.net/browse/OSDEV-273?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OSDEV-273] Fix issue with the lowercase strings, add tests

---

doc/release/RELEASE-NOTES.md
src/django/api/serializers/facility/facility_claim_serializer.py
src/django/api/tests/test_facility_claim_serializer.py
src/react/src/__tests__/components/DashboardClaimsListTable.test.js
src/react/src/components/DashboardClaimsListTable.jsx
src/react/src/components/DashboardClaimsListTableHeader.jsx
src/react/src/util/propTypes.js
src/react/src/util/util.js

[OSDEV-1036](https://opensupplyhub.atlassian.net/browse/OSDEV-1036) **Claims. Add a sortable "claim decision" column to claims admin page.**
- added new data point 'claim_decision' to response & create new column on page
- update styling & location of the field
- update sort logic for null value
[OSDEV-1036]: https://opensupplyhub.atlassian.net/browse/OSDEV-1036?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OSDEV-1036] Claims. Add a sortable "claim decision" column to claims admin page. 

---

doc/release/RELEASE-NOTES.md
src/react/package.json
src/react/src/__tests__/components/DashboardClaimsListTable.test.js
src/react/src/util/util.js
src/react/yarn.lock

Introduce right sorting for accented strings as follow-up patch for [OSDEV-272](https://opensupplyhub.atlassian.net/browse/OSDEV-272)
[OSDEV-272]: https://opensupplyhub.atlassian.net/browse/OSDEV-272?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OSDEV-272] Adjust sorting for accented strings

---

doc/release/RELEASE-NOTES.md
src/django/api/facility_actions/processing_facility_api.py
src/django/api/facility_actions/processing_facility_list.py
src/django/api/matching.py
src/django/api/models/transactions/clean_facilitylistitems.py
src/django/api/views/facility/facilities_view_set.py
src/django/oar/settings.py

- Introduced a general format for all Python logs by updating the Django `LOGGING` constant.
- Disabled propagation for the `django` logger to the `root` logger to avoid log duplication.
- Removed unnecessary calls to the `basicConfig` method since only the configuration defined in the `LOGGING` constant in the settings.py file is considered valid by the current Django app.
Please refer to [the official documentation](https://docs.djangoproject.com/en/3.2/topics/logging/) on configuring Python logging in a Django app.

Configure error logging through django settings

---

doc/release/RELEASE-NOTES.md
src/django/api/reports/history_of_contributor_uploads.sql

[OSDEV-981](https://opensupplyhub.atlassian.net/browse/OSDEV-981) Reporting. History of contributor uploads.
* rewritten the formula for uploads per year
* changed the task description
[OSDEV-981]: https://opensupplyhub.atlassian.net/browse/OSDEV-981?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Hotfix [OSDEV-981] Reporting. History of contributor uploads.

---

.github/workflows/deploy_to_aws.yml

This change allows pushing database-anonimyzer image to ECR.
Must be merged only after merging configuration changes.

Allow push database anonymizer image to ECR

---

doc/release/RELEASE-NOTES.md
src/react/src/__tests__/utils.tests.js
src/react/src/components/ContributeForm.jsx
src/react/src/util/constants.jsx
src/react/src/util/util.js

[OSDEV-1145](https://opensupplyhub.atlassian.net/browse/OSDEV-1145?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ) (https://opensupplyhub.atlassian.net/browse/OSDEV-1145) Error message appearing as a red dot with no context.
* Simplified displaying logic of errors 
* Changed error prop type
The task which was implemented [OSDEV-1105](https://opensupplyhub.atlassian.net/browse/OSDEV-1105)
[OSDEV-1145]: https://opensupplyhub.atlassian.net/browse/OSDEV-1145?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[OSDEV-1105]: https://opensupplyhub.atlassian.net/browse/OSDEV-1105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OSDEV-1145]  Fix the error handling for errors from the BE

---

doc/release/RELEASE-NOTES.md
src/logstash/pipeline/sync_production_locations.conf

- This PR removes the unintended behaviour where OpenSearch applies [dynamic mapping](https://opensearch.org/docs/latest/field-types/#dynamic-mapping) instead of [explicit mapping](https://opensearch.org/docs/latest/field-types/#explicit-mapping) defined in the Logstash app. For instance, this is extremely important for the `coordinates` field, which, by dynamic mapping, is recognized as a simple object with `lat` and `lon` properties. However, it should be of [the geo_point type](https://opensearch.org/docs/latest/field-types/supported-field-types/geo-point/), which is manually set via the `production_locations.json` index template to enable [Geopolygon queries](https://opensearch.org/docs/latest/query-dsl/geo-and-xy/geopolygon/) for the search performed by drawing the boundary on the …

Disable using legacy template endpoint for OpenSearch

---

deployment/terraform/opensearch.tf
deployment/terraform/variables.tf
doc/release/RELEASE-NOTES.md

Bugfix: Make the OpenSearch domain name unique per environment to avoid conflicts.
The domain name was shortened due to this restriction: `invalid value for domain_name (must start with a lowercase alphabet and be at least 3 and no more than 28 characters long. Valid characters are a-z (lowercase letters), 0-9, and - (hyphen).)`

Make the OpenSearch domain name unique per environment to avoid conflicts.

---

src/django/api/management/commands/post_deployment.py

Removed the triggering of indexing in the post-deployment command since it is not necessary for the 1.18.0 release.

Remove triggering indexing in the post deployment command

---

doc/release/RELEASE-NOTES.md
src/react/src/components/LoginForm.jsx

[OSDEV-1176](https://opensupplyhub.atlassian.net/browse/OSDEV-1176) - Fix the spelling of the word 'password' on the Log In page.
Fixed a spelling mistake in the label for the password field on the LogIn page. After the fix, the label reads "Password".

[OSDEV-1176] Fix the spelling of the word 'password' on the Log In page.

---

src/django/api/services/search.py
src/django/api/tests/test_opensearch_response_formatter.py

Follow-up PR for [OSDEV-1006](https://opensupplyhub.atlassian.net/browse/OSDEV-1006)
Restructure OpenSearch response to this format:
```
{
"count": <Number (total hits in DB)>
"data": <array[Object]>
}
```
The `<array[Object]>` is represented by array of production locations entries.
[OSDEV-1006]: https://opensupplyhub.atlassian.net/browse/OSDEV-1006?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OSDEV-1006] Format response output

---

src/django/api/views/v1/opensearch_query_builder/opensearch_query_director.py

Follow up PR for [OSDEV-982](https://opensupplyhub.atlassian.net/browse/OSDEV-982) that brings back missing os_id param setting that has been lost while merge conflict resolving.
[OSDEV-983]: https://opensupplyhub.atlassian.net/browse/OSDEV-983?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[OSDEV-982]: https://opensupplyhub.atlassian.net/browse/OSDEV-982?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OSDEV-982] Bring back missing os_id param setting

---

src/django/api/serializers/v1/opensearch_common_validators/size_validator.py
src/django/api/serializers/v1/production_locations_serializer.py

Follow-up PR [OSDEV-1184](https://opensupplyhub.atlassian.net/browse/OSDEV-1184) that introduces validation of the size parameter.
Size parameter:
1. Should be positive integer
2. Should be less or equal to our current OpenSearch output limit (250 entries) 
[OSDEV-1184]: https://opensupplyhub.atlassian.net/browse/OSDEV-1184?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OSDEV-1184] Add size param validation

---

doc/release/RELEASE-NOTES.md
src/logstash/indexes/production_locations.json

[OSDEV-1103](https://opensupplyhub.atlassian.net/browse/OSDEV-1103) API v1/production-locations. Enable accent-insensitive search in OpenSearch for the production location name and address.
Enabled accent-insensitive search for `name` and `address` fields of production location by designing the index mapping to do ASCII folding for search tokens.
[OSDEV-1103]: https://opensupplyhub.atlassian.net/browse/OSDEV-1103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OSDEV-1103] Enable accent-insensitive search in OpenSearch for the production location name and address.

---

doc/release/RELEASE-NOTES.md
src/django/api/views/v1/opensearch_query_builder/opensearch_query_director.py

[OSDEV-1103](https://opensupplyhub.atlassian.net/browse/OSDEV-1103) - API v1/production-locations. Enable accent-insensitive search in OpenSearch for the production location name and address.
Change query_type for `name` and `name_local` fields from `terms` to `match`.
[OSDEV-1103]: https://opensupplyhub.atlassian.net/browse/OSDEV-1103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OSDEV-1103] Change query_type for name and name_local fields from `terms` to `match` to enable ASCII search.

---

doc/release/RELEASE-NOTES.md

[[OSDEV-1173](https://opensupplyhub.atlassian.net/browse/OSDEV-1173)] Include the following release instructions in the release notes for version 1.19:
- Before deploying to an existing environment, manually delete the related EFS storage, OpenSearch domain, and stop all tasks of the Logstash service in the appropriate ECS cluster. This is necessary to apply the new mapping for the production-locations OpenSearch index.
[OSDEV-1173]: https://opensupplyhub.atlassian.net/browse/OSDEV-1173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OSDEV-1173] Include release instructions in the release notes for version 1.19

---

doc/release/RELEASE-NOTES.md
src/django/api/serializers/facility/facility_match_serializer.py
src/django/api/tests/test_facility_match_serializer.py
src/react/src/__tests__/components/FacilityListItemsConfirmationTableRowItem.test.js
src/react/src/components/BadgeVerified.jsx
src/react/src/components/FacilityListItemsConfirmationTableRow.jsx
src/react/src/components/FacilityListItemsConfirmationTableRowItem.jsx
src/react/src/util/styles.js

[OSDEV-1025](https://opensupplyhub.atlassian.net/browse/OSDEV-1025) - Data Moderation. Add the claim badge to C/R moderation screen.
- Added the claim badge to the facility details on the C/R moderation screen when the facility has an approved claim.
- Added the `get_is_claimed` method to the `FacilityMatchSerializer` that returns a boolean value depending on whether the matched facility has an approved claim or not.
[OSDEV-1025]: https://opensupplyhub.atlassian.net/browse/OSDEV-1025?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OSDEV-1025] Add the claim badge to C/R moderation screen

---

src/django/api/management/commands/post_deployment.py

Remove the calling of the `index_facilities_new` command from the `post_deployment` command after release 1.20.

Remove calling of `index_facilities_new` command from the `post_deployment` command

---

.github/workflows/deploy_to_aws.yml
doc/release/RELEASE-NOTES.md

Prevent automated deployment to AWS after creating tags for `sandbox` and `production`.
- The code responsible for triggering workflows on pushes to tags starting with `sandbox` or `production` was commented out to prevent automated deployment to AWS.
- The 'Release Instructions' section of the `RELEASE-NOTES.md` has been updated with a description of how to manually run the deployment to AWS.

Prevent automated deployment to AWS after creating tags for `sandbox` and `production`

---

doc/release/RELEASE-NOTES.md
src/django/Dockerfile
src/django/requirements.txt

Changed the base image in the Django app Dockerfile to use a Debian 11 instead of Debian 10 as the PostgreSQL 13 repository support for Debian 10 has been ended.

[OSDEV-1372] Use a new base docker image for Django

---

deployment/environments/terraform-development.tfvars
deployment/environments/terraform-preprod.tfvars
deployment/environments/terraform-production.tfvars
deployment/environments/terraform-staging.tfvars
deployment/environments/terraform-test.tfvars
deployment/terraform/container_service.tf
deployment/terraform/task-definitions/app.json
deployment/terraform/variables.tf
doc/release/RELEASE-NOTES.md
docker-compose.yml
src/dedupe-hub/api/app/utils/constants.py
src/django/api/adapters.py
src/django/api/mail.py
src/django/api/management/commands/reprocess_geocode_failures.py
src/django/api/serializers/user/user_password_reset_serializer.py
src/django/api/views/facility/facility_list_view_set.py
src/django/oar/settings.py

- Removed the `py_environment` Terraform variable, as it appeared to be a duplicate of the `environment` variable.
- Passed the correct environment values to the ECS task definition for the Django containers in all environments, especially in the Preprod and Development environments, to avoid misunderstandings and incorrect interpretations of the values previously passed via `py_environment`.
- Introduced a *Local* environment specifically for local development to avoid duplicating variable values with the AWS-hosted *Development* environment.

Fixed a bug related to environment variable management

---

doc/release/RELEASE-NOTES.md
src/django/api/management/commands/post_deployment.py
src/django/api/models/facility/facility.py
src/django/api/tests/test_facility_claim_admin_dashboard.py
src/django/api/tests/test_facility_history_endpoint.py
src/django/api/tests/test_facility_merge.py
src/django/api/tests/test_opensearch_relevant_data.py
src/django/api/views/facility/facilities_view_set.py
src/django/api/views/facility/facility_claim_view_set.py

[OSDEV-1102](https://opensupplyhub.atlassian.net/browse/OSDEV-1102) - API. Propagate production location updates to OpenSearch data source via refreshing `updated_at` field in `api_facility` table.
List of cases where updated data should appear in OpenSearch:
- Claim process: approve, reject, deny, claim
- Claim details 
- Merge facilities (Dashboard)
Fixed the tests for the facility history, as the save operation increases the number of actions saved to the facility history with the status FacilityHistoryActions.OTHER.
[OSDEV-1102]: https://opensupplyhub.atlassian.net/browse/OSDEV-1102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OSDEV-1102] Propagate production location updates to OpenSearch

---

doc/release/RELEASE-NOTES.md
src/react/src/__tests__/components/SearchByOsIdSuccessResult.test.js
src/react/src/components/Contribute/SearchByOsIdResult.jsx
src/react/src/components/Contribute/SearchByOsIdSuccessResult.jsx
src/react/src/util/propTypes.js
src/react/src/util/styles.js

[OSDEV-1127](https://opensupplyhub.atlassian.net/browse/OSDEV-1127) - SLC. Implement OS ID search. 
This PR adds a country name to the "Search by OS ID" result screen to provide users with a clearer geographical context for production location.
Changes:
- Modified Components:
- `SearchByOsIdResult.jsx`: Updated logic to pass the country name to the result display.
- `SearchByOsIdSuccessResult.jsx`:  Updated to render the country name field as part of the result view.
- Prop Types:
- Extended `productionLocationPropType` to include a `country` object for ensuring correct data type validation.
- Styling:
- Updated styles in `makeSearchByOsIdResultStyles` to ensure the country name is properly displayed and aligned with the rest of the layout.
- Tests:
- Updated unit tests for the …

[OSDEV-1127] Add country name to the "Search by OS ID" result screen.

---

.github/workflows/deploy_to_aws.yml
doc/release/RELEASE-NOTES.md

Updated the reset database step in the `restore_database` job of the Deploy to AWS GitHub workflow to upload CSV location list files to S3 for parsing during the DB reset.

[OSDEV-1039] Fix DB reset

---

src/react/src/__tests__/components/SearchByOsIdTab.test.js
src/react/src/components/Contribute/SearchByOsIdTab.jsx

[OSDEV-1127](https://opensupplyhub.atlassian.net/browse/OSDEV-1127) - SLC. Implement OS ID search.
In this PR, the helper text for the OS ID input was updated to match the layouts.
[OSDEV-1127]: https://opensupplyhub.atlassian.net/browse/OSDEV-1127?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OSDEV-1127] Update the helper text for the OS ID input 

---

src/react/src/__tests__/components/SearchByOsIdTab.test.js
src/react/src/components/Contribute/SearchByOsIdTab.jsx

[OSDEV-1127](https://opensupplyhub.atlassian.net/browse/OSDEV-1127) - SLC. Implement OS ID search.
In this PR, the helper text for the OS ID input was updated to match the layouts.
[OSDEV-1127]: https://opensupplyhub.atlassian.net/browse/OSDEV-1127?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OSDEV-1127] Update the helper text for the OS ID input

---

deployment/environments/terraform-staging.tfvars
doc/release/RELEASE-NOTES.md

The number of ECS tasks for the Django app in the staging environment has been reduced from 6 to 4, while maintaining system stability.

Resource allocation has been optimized for the staging environment

---

deployment/terraform/opensearch.tf
doc/release/RELEASE-NOTES.md
docker-compose.yml

Right now, the deployment to AWS is failing because version 2.17 isn't supported yet. See the logs here: https://github.com/opensupplyhub/open-supply-hub/actions/runs/11579269192/job/32235103967.
That's why the version was decreased to 2.15, the latest version supported by AWS.

Decreased the OpenSearch version to 2.15, the latest version supported by AWS.

---

doc/release/RELEASE-NOTES.md

Right now, to enable access from EC2 to OpenSearch, the IAM ARN of the special Terraform user needs to be added to the master user settings associated with the OpenSearch instance. Since it’s not possible to set multiple master users via Terraform, you will need to add one more manually through the AWS console, as this is permitted.
As the OpenSearch instance will be recreated during the release of version 1.24, the necessary instructions have been provided in the corresponding release notes 1.24 to reestablish access from EC2 to OpenSearch for clearing OpenSearch indexes.

Updated RELEASE-NOTES.md file for 1.24 version

---

doc/release/RELEASE-NOTES.md
src/django/api/throttles.py

In this PR, the tile generation request rate is throttled to 30 requests per minute. This solution aims to reduce the risk of outages in the production environment.
* Changed the parent class of TilesThrottle to SimpleRateThrottle.
* Introduced a minimal implementation of the TilesThrottle class

[OSDEV-1387] Make tile generation to be throttled 30/minutes

---

doc/release/RELEASE-NOTES.md
src/django/api/throttles.py
src/django/api/tiler.py
src/django/api/views/tile/get_tile.py

Reimplemented tiles generation with PostgreSQL+PostGIS
- avoid using the JOIN + GROUP BY clause. This change reduces the number of subqueries and their asymptotic complexity.
- Enhanced error handling for empty results in facility grid vector tile generation.
- Introduced a constant HI_LIMIT for improved query logic.
- Removed throttling from the get_tile function, allowing unrestricted access.

[OSDEV-1387] [hotfix 1.23.1] Improve tile generation performance by eliminating `group by` clause

---

src/django/api/tiler.py

Use tuple concatenation instead of converting to array

[OSDEV-1387] (Hotfix 1.23.1) Fix exception while generating tiles for custom area on Map

---

deployment/environments/terraform-production.tfvars
doc/release/RELEASE-NOTES.md

In this PR the RDS instance for `production` has been upgraded to `db.m6in.4xlarge` and configured to operate in a single Availability Zone.

Upgrade the RDS instance for `production` and configure it to operate in a single Availability Zone.

---

doc/release/RELEASE-PROTOCOL.md

In this PR the section `Release Schedule` in the Release Protocol was updated after release v1.23.

Update the release schedule in the release protocol after release v1.23

---

deployment/environments/terraform-preprod.tfvars
deployment/environments/terraform-production.tfvars
doc/release/RELEASE-NOTES.md

- Increased memory for the Dedupe Hub instance from 8GB to 12GB in `production` & `pre-prod` environments.

Increased memory for the Dedupe Hub

---

doc/release/RELEASE-NOTES.md
src/django/api/management/commands/post_deployment.py

In this PR, the `reindex_database` command has been added to the `post_deployment` command.

Call `reindex_database` in the `post_deployment` command

---

doc/release/RELEASE-NOTES.md
src/django/api/constants.py
src/django/api/exceptions.py
src/django/api/views/facility/facilities_view_set.py
src/django/api/views/facility/facility_list_view_set.py

[OSDEV-1467](https://opensupplyhub.atlassian.net/browse/OSDEV-1467) Implemented disabling endpoint POST /api/facilities/ during the release process. It is raising an error message with status code 503.
[OSDEV-1467]: https://opensupplyhub.atlassian.net/browse/OSDEV-1467?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OSDEV-OSDEV-1467] Fix blocking API facility create endpoint for 1.25

---

src/django/api/views/facility/facilities_view_set.py

Limit the page number to 100 for the API/facilities GET endpoint.

Limit page number for api/facilities GET endpoint

---

deployment/environments/terraform-production.tfvars

Increased storage size to 256 GB for RDS in Production environment to process more data.

Increased storage size for RDS in prod

---

src/django/api/moderation_event_actions/approval/add_production_location.py
src/django/api/tests/test_moderation_events_add_production_location.py

[OSDEV-1410](https://opensupplyhub.atlassian.net/browse/OSDEV-1410) - Moderation. Implement POST /api/moderation-events/{moderation_id}/production-locations endpoint.
In this PR, a fix was added for the processing of geocode results during the creation of a new production location based on the moderation event.
[OSDEV-1410]: https://opensupplyhub.atlassian.net/browse/OSDEV-1410?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OSDEV-1410] Fix processing of geocode results for POST /api/moderation-events/{moderation_id}/production-locations endpoint

---

deployment/environments/terraform-preprod.tfvars
deployment/environments/terraform-production.tfvars
deployment/environments/terraform-test.tfvars
doc/release/RELEASE-NOTES.md

In light of recent instances(on 12/03/2024 UTC and 12/04/2024 UTC) where the current RDS disk storage space limit was reached in Production, the RDS storage size has been increased to `256 GB` in the Production, Test, and Pre-prod environments to accommodate the processing of larger volumes of data. The configurations for the Test and Pre-prod environments have also been updated to maintain parity with the Production environment.

Increased RDS storage space in Production, Test, and Pre-prod environments.

---

.github/workflows/db_apply_anonimized.yml
.github/workflows/deploy_to_aws.yml
.github/workflows/release-deploy.yml
deployment/clear_opensearch/clear_opensearch.sh.tpl
deployment/clear_opensearch/run.sh.tpl
doc/release/RELEASE-NOTES.md
doc/release/RELEASE-PROTOCOL.md

It was found that clearing OpenSearch indexes didn’t work properly because the templates weren’t cleared. After updating the index mappings within the index template files, the index template remained unchanged because only the indexes were deleted during deployment, not both the indexes and their templates. This caused conflicts and prevented developers' updates from being applied to the OpenSearch indexes.
This issue has been fixed by adding additional requests to delete the appropriate index templates to the `clear_opensearch.sh.tpl` script, which is triggered when clearing OpenSearch during deployment to any environment.

Fix OpenSearch index mapping updates

---

doc/release/RELEASE-NOTES.md
src/django/api/views/v1/moderation_events.py
src/tests/v1/test_moderation_events.py

[OSDEV-1482](https://opensupplyhub.atlassian.net/browse/OSDEV-1482) GET api/v1/moderation-events/{moderation_id} should return single response instead of array
- Updated response format and added handling for 404
[OSDEV-1482]: https://opensupplyhub.atlassian.net/browse/OSDEV-1482?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OSDEV-1482] GET api/v1/moderation-events/{moderation_id} should return single response instead of array

---

doc/release/RELEASE-NOTES.md
src/react/src/components/DashboardGeocoder.jsx
src/react/src/components/FacilitiesMap.jsx
src/react/src/components/VectorTileFacilitiesMap.jsx

[OSDEV-1511](https://opensupplyhub.atlassian.net/browse/OSDEV-1511) Map doesn't render properly on Dashboard / Geocoder and Settings / Embed pages
- Updated google maps api version to 3.59 (3.51-3.55 not supported)
[OSDEV-1511]: https://opensupplyhub.atlassian.net/browse/OSDEV-1511?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Release 1.26.0 - [OSDEV-1511] Map doesn't render properly on Dashboard / Geocoder and Settings / Embed pages

---

doc/release/RELEASE-NOTES.md
src/react/src/components/DashboardGeocoder.jsx
src/react/src/components/FacilitiesMap.jsx
src/react/src/components/VectorTileFacilitiesMap.jsx

[OSDEV-1511](https://opensupplyhub.atlassian.net/browse/OSDEV-1511) Map doesn't render properly on Dashboard / Geocoder and Settings / Embed pages
- Updated google maps api version to 3.59 (3.51-3.55 not supported)
[OSDEV-1511]: https://opensupplyhub.atlassian.net/browse/OSDEV-1511?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OSDEV-1511] Map doesn't render properly on Dashboard / Geocoder and Settings / Embed pages

---

doc/release/RELEASE-NOTES.md
src/django/api/tests/test_moderation_events_query_builder.py
src/django/api/views/v1/opensearch_query_builder/moderation_events_query_builder.py

[OSDEV-1493](https://opensupplyhub.atlassian.net/browse/OSDEV-1493) Moderation. Moderation Queue Page (integration) - sorting issue and 500 error for localization
- Fixed an issue where the backend sorts countries not by `name` but by their `alpha-2 codes` in `GET /api/v1/moderation-events/` endpoint.
[OSDEV-1493]: https://opensupplyhub.atlassian.net/browse/OSDEV-1493?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OSDEV-1493] Moderation. Moderation Queue Page (integration) - sorting issue and 500 error for localization

---

deployment/environments/terraform-development.tfvars
deployment/environments/terraform-preprod.tfvars
deployment/environments/terraform-production.tfvars
deployment/environments/terraform-staging.tfvars
deployment/environments/terraform-test.tfvars
doc/release/RELEASE-NOTES.md

Right-sized the resources for Django containers across all environments and the RDS instance in the Production and Preprod environments. This will result in a savings of approximately $2,481. The following changes have been made:
- Production:
- RDS instance type was changed from `db.m6in.8xlarge` to `db.m6in.4xlarge`.
- ECS tasks for Django containers: the number was reduced from `12` to `10`, and memory was reduced from `8GB` to `4GB`.
- Preprod:
- RDS instance type was changed from `db.m6in.8xlarge` to `db.m6in.4xlarge`.
- ECS tasks for Django containers: the number was reduced from `12` to `10`, and memory was reduced from `8GB` to `4GB`.
- These changes were made to maintain parity with the Production environment, as it is a copy of that environment.
- Staging:
- ECS tasks for Django …

Right-sized ECS and RDS resources

---

doc/release/RELEASE-NOTES.md
src/django/api/templates/mail/approved_facility_claim_contributor_notice_body.html
src/django/api/templates/mail/approved_facility_claim_contributor_notice_body.txt
src/django/api/templates/mail/approved_facility_claim_contributor_notice_subject.txt

Updated the email text, added links and bolded keywords.

[OSDEV-1383] Approved facility claim contributor notice copy update

---

doc/release/RELEASE-NOTES.md
src/django/api/tests/test_contributors_list_api_endpoint.py
src/django/api/views/contributor/all_contributors.py

[OSDEV-1474](https://opensupplyhub.atlassian.net/browse/OSDEV-1474) Add contributor type to /api/contributors/ endpoint
- Added contributor type value to response of `/api/contributors/` endpoint
- Updated unit test
[OSDEV-1474]: https://opensupplyhub.atlassian.net/browse/OSDEV-1474?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OSDEV-1474] Add contributor type to /api/contributors/ endpoint

---

doc/release/RELEASE-NOTES.md
src/django/api/templates/mail/report_result_body.html
src/django/api/templates/mail/report_result_body.txt

Updated the automated email for closure reports (report_result( to remove the term "Rejected" for an improved user experience. Added link to Closure Report policy and instructions to submit a reopening report to provide users with more information on the process.

Osdev 1376 closure report. updating auto email response to remove the word 'rejected'

---

deployment/clear_opensearch/clear_opensearch.sh.tpl
doc/release/RELEASE-NOTES.md
src/django/api/constants.py
src/django/api/moderation_event_actions/creation/dtos/create_moderation_event_dto.py
src/django/api/moderation_event_actions/creation/moderation_event_creator.py
src/django/api/tests/test_location_contribution_strategy.py
src/django/api/tests/test_production_locations_partial_update.py
src/django/api/views/v1/production_locations.py
src/logstash/indexes/moderation_events.json

[[OSDEV-1336](https://opensupplyhub.atlassian.net/browse/OSDEV-1336)]
- Introduced a new PATCH `/api/v1/production-locations/{os_id}/` endpoint based on the API v1 specification. This endpoint allows the creation of a new moderation event for updating the production location with the given details. Basically, the endpoint can be used to contribute to an existing location.
- Dynamic mapping for the new fields in the `moderation-events` index has been disabled for those that don't have an explicit mapping defined. This change helps avoid indexing conflicts, such as when a field is initially indexed with one data type (e.g., long), but later an entry with a different data type for the same field is indexed, causing the entire entry to fail indexing. After this change, fields with an explicit …

[OSDEV-1336] SLC. Implement PATCH api/v1/production-locations/{os_id}/

---

doc/release/RELEASE-NOTES.md
src/react/src/__tests__/components/DashboardModerationQueueListTable.test.js
src/react/src/components/Dashboard/DashboardModerationQueueListTable.jsx

[OSDEV-1533](https://opensupplyhub.atlassian.net/browse/OSDEV-1533) - The presentation of the `Moderation Decision Date` in the `Moderation Queue` table has been corrected. If the "status_change_date" is missing in the object, it now displays as "N/A".
[OSDEV-1533]: https://opensupplyhub.atlassian.net/browse/OSDEV-1533?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OSDEV-1533] Moderation Decision Date should be N/A if "status_change_date" is absent in object

---

doc/release/RELEASE-NOTES.md
src/react/src/components/Dashboard/DashboardModerationQueue.jsx

[OSDEV-1532](https://opensupplyhub.atlassian.net/browse/OSDEV-1532) - Fixed the date range picker on the `Moderation Queue` page. A Data Moderator can change the Before date even if an Error message is displayed.
[OSDEV-1532]: https://opensupplyhub.atlassian.net/browse/OSDEV-1532?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OSDEV-1532] Fix date filter on the Moderation Queue page

---

src/react/src/components/Contribute/SearchByNameAndAddressTab.jsx
src/react/src/util/COLOURS.js

Fixed styles on the Search by name and address page according to the design:
- changed border color in Country Select from blue to purple
- made border radius:0
- fixed placeholder opacity
- removed unnecessary changes and classes

Fix styles on the Search by name and address page according to the design

---

doc/release/RELEASE-NOTES.md
src/django/api/os_id.py
src/django/api/services/moderation_events_service.py
src/django/api/tests/test_moderation_events_update_production_location.py

[OSDEV-1556](https://opensupplyhub.atlassian.net/browse/OSDEV-1556) - Moderation Queue: PATCH: /api/v1/moderation-events/{moderation_id}/production-locations/{os_id}: Error 500 if os_id doesn't exist
The validation of `os_id` for the PATCH `/api/v1/moderation-events/{moderation_id}/production-locations/{os_id}/` endpoint was fixed.
[OSDEV-1556]: https://opensupplyhub.atlassian.net/browse/OSDEV-1556?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OSDEV-1556] Fix validation of os_id during updating production location via moderation event.

---

doc/release/RELEASE-NOTES.md

The release 1.27.0 date has been changed to January 11, 2025.

Correct the release 1.27.0 date

---

doc/release/RELEASE-NOTES.md
src/django/api/templates/mail/api_limit_body.html
src/django/api/templates/mail/api_limit_body.txt
src/django/api/templates/mail/api_limit_subject.txt

Removed an outdated link referring to OAR. Improved the language for clarity and added the correct process for contacting the OS Hub team when the user reaches their API calls limit.

[OSDEV-1579] Update copy api limit automated emails

---

doc/release/RELEASE-PROTOCOL.md

Added information about the person responsible for the 1.28, and 1.29 release.

Add next responsible person for 1.28, 1.29 release

---

deployment/environments/terraform-development.tfvars
doc/release/RELEASE-NOTES.md

Some of the resources related to the Development AWS environment still have the `stg` prefix, which can be confusing since we also have a Staging environment with the same prefix. To clarify the resource names, including the database instance, the prefix has been updated from `stg` to `dev` for the development environment.

Updated the prefix from "stg" to "dev" for the Development environment in the AWS infrastructure.

---

doc/release/RELEASE-NOTES.md
src/react/src/Routes.jsx

[OSDEV-1626](https://opensupplyhub.atlassian.net/browse/OSDEV-1626) **SLC. Update URL for "Add Data" functionality on site to hide SLC entry point.**
- Temporarily hid the new contribution page `Add Location Data` and re-enabled the old navigation to the `List Upload` page via the `/contribute` path.
[OSDEV-1626]: https://opensupplyhub.atlassian.net/browse/OSDEV-1626?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Hotfix - [OSDEV-1626] SLC. Update URL for "Add Data" functionality on site to hide SLC entry point.

---

src/react/src/__tests__/components/ProductionLocationDialog.test.js
src/react/src/components/Contribute/ProductionLocationDialog.jsx
src/react/src/components/Contribute/ProductionLocationInfo.jsx

Follow-up fix for [OSDEV-1365](https://opensupplyhub.atlassian.net/browse/OSDEV-1365)
Disable claim button when moderation event on new productino location is REJECTED.
[OSDEV-1365]: https://opensupplyhub.atlassian.net/browse/OSDEV-1365?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OSDEV-1365] Disable claim button when moderation event on new productino location is REJECTED

---

doc/release/RELEASE-NOTES.md
src/django/api/constants.py
src/django/api/serializers/v1/opensearch_common_validators/coordinates_validator.py
src/django/api/serializers/v1/opensearch_common_validators/geo_bounding_box_validator.py
src/django/api/serializers/v1/production_locations_serializer.py
src/django/api/tests/test_production_locations_query_builder.py
src/django/api/tests/test_v1_utils.py
src/django/api/views/v1/opensearch_query_builder/opensearch_query_director.py
src/django/api/views/v1/opensearch_query_builder/production_locations_query_builder.py
src/django/api/views/v1/parameters_list.py
src/django/api/views/v1/utils.py
src/tests/v1/test_production_locations.py

[OSDEV-1577](https://opensupplyhub.atlassian.net/browse/OSDEV-1577) - [API] Add Geo-bounding box support to the production locations endpoint.
Added geo-bounding box query support to the GET `/api/v1/production-locations/` endpoint. To filter production locations whose geopoints fall within the bounding box, it is necessary to specify valid values for the parameters `geo_bounding_box[top]`, `geo_bounding_box[left]`, `geo_bounding_box[bottom]`, and `geo_bounding_box[right]`. 
The validation rules are as follows:
- All coordinates of the geo-boundary box (top, left, bottom, right) must be provided.
- All values must be integers.
- The top and bottom coordinates must be between -90 and 90.
- The left and right coordinates must be between -180 and 180.
- The top must be greater than the …

[OSDEV-1577] Add geo-bounding box support to the GET `/v1/production-locations/` endpoint

---

deployment/environments/terraform-development.tfvars
deployment/environments/terraform-production.tfvars
deployment/environments/terraform-staging.tfvars
deployment/environments/terraform-test.tfvars
doc/release/RELEASE-NOTES.md

- [OSDEV-1515](https://opensupplyhub.atlassian.net/browse/OSDEV-1515) - Removed `rds_allow_major_version_upgrade` and `rds_apply_immediately` from the environment tfvars files (e.g., terraform-production.tfvars) to set them to `false` again, as the default values in `/deployment/terraform/variables.tf` are `false`. This is necessary to prevent unintended PostgreSQL major version upgrades since the target PostgreSQL 16.3 version has been reached.
- Update the name of the step in the `post_deploy` job of the "DB - Apply Anonymized DB" workflow to make it more informative.
[OSDEV-1515]: https://opensupplyhub.atlassian.net/browse/OSDEV-1515?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OSDEV-1515] Prevented unintended PostgreSQL major version upgrades.

---

doc/release/RELEASE-NOTES.md
src/react/src/Routes.jsx
src/react/src/components/AddLocationData.jsx
src/react/src/util/constants.jsx
src/react/src/util/styles.js

[OSDEV-1589](https://opensupplyhub.atlassian.net/browse/OSDEV-1589) **[FE] Layout issue on "contribute" page**
- Updated styles by @anna-bondar11  & @mazursasha1990 ticket comments
- Created temporary route `/contribute-new` for testing (need to remove in [OSDEV-1607](https://opensupplyhub.atlassian.net/browse/OSDEV-1607))
[OSDEV-1589]: https://opensupplyhub.atlassian.net/browse/OSDEV-1589?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[OSDEV-1607]: https://opensupplyhub.atlassian.net/browse/OSDEV-1607?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OSDEV-1589] [FE] Layout issue on "contribute" page

---

doc/release/RELEASE-NOTES.md
src/react/src/components/Contribute/ProductionLocationInfo.jsx

Fix [OSDEV-1696](https://opensupplyhub.atlassian.net/browse/OSDEV-1696)
1. Add loader on single production location fetch.
2. Add error handling using toastify component.
3. Add cleanup hook to clear production location data on component unmount.
[OSDEV-1696]: https://opensupplyhub.atlassian.net/browse/OSDEV-1696?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OSDEV-1696] Add loader to the production location info

---

doc/release/RELEASE-NOTES.md
src/django/api/serializers/v1/number_of_workers_serializer.py
src/react/src/__tests__/utils.tests.js
src/react/src/util/util.js

[OSDEV-1748](https://opensupplyhub.atlassian.net/browse/OSDEV-1748) Moderation Queue. Align SLC with current v1/production-locations validation.
- changed func parseContribData (removed all not filled fields)
- removed validation for number_of_workers min >= max
[OSDEV-1748]: https://opensupplyhub.atlassian.net/browse/OSDEV-1748?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OSDEV-1748] Align SLC with current v1/production-locations validation.

---

.github/workflows/deploy_to_aws.yml
doc/release/RELEASE-NOTES.md

Fix: [OSDEV-1692](https://opensupplyhub.atlassian.net/browse/OSDEV-1692) to release v.2.0 branch. Update cache dependencies due to Ubuntu 20 image runner deprecation. See [link](https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down).
[OSDEV-1692]: https://opensupplyhub.atlassian.net/browse/OSDEV-1692?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update cache dependencies

---

.github/workflows/deploy_to_aws.yml
deployment/terraform/cdn.tf
doc/release/RELEASE-NOTES.md

[[OSDEV-899](https://opensupplyhub.atlassian.net/browse/OSDEV-899)]
The default redirection of 404 and 403 responses to the /index.html file in the S3 bucket, which CloudFront receives from the S3 bucket with the React app, causes 403 and 404 responses from Django API endpoints to be redirected to the same S3 bucket. This means that endpoints, such as those requiring admin access, won't return the correct JSON response for a 403 error. Instead, the HTML file will be returned with a 200 status code.
Additionally, removing this redirection rule for 403 errors will cause the React app to break, as CloudFront won't be able to locate the React paths that the client sends in the S3 bucket. Requests won't be rerouted to index.html, which is the main entry point for the React app.
For now, the …

[OSDEV-899] Revert the splitting of the Django and React app.

---

.github/workflows/deploy_to_aws.yml
deployment/terraform/cdn.tf
doc/release/RELEASE-NOTES.md

[[OSDEV-899](https://opensupplyhub.atlassian.net/browse/OSDEV-899)]
Backmerge of the [PR](https://github.com/opensupplyhub/open-supply-hub/pull/529).
The default redirection of 404 and 403 responses to the /index.html file in the S3 bucket, which CloudFront receives from the S3 bucket with the React app, causes 403 and 404 responses from Django API endpoints to be redirected to the same S3 bucket. This means that endpoints, such as those requiring admin access, won't return the correct JSON response for a 403 error. Instead, the HTML file will be returned with a 200 status code.
Additionally, removing this redirection rule for 403 errors will cause the React app to break, as CloudFront won't be able to locate the React paths that the client sends in the S3 bucket. Requests won't be …

[OSDEV-899][Backmerge] Revert the splitting of the Django and React app.

---

doc/release/RELEASE-NOTES.md
src/django/api/serializers/v1/production_location_schema_serializer.py
src/django/api/tests/test_production_locations_create.py
src/django/api/tests/test_production_locations_partial_update.py

Fix [https://opensupplyhub.atlassian.net/browse/OSDEV-1806](https://opensupplyhub.atlassian.net/browse/OSDEV-1806)
1. Set `parent_company` field as regular char field.
2. Updated tests for POST and PATCH `v1/production-locations`

[OSDEV-1806] Fix parent company validation

---

doc/release/RELEASE-NOTES.md
src/react/src/__tests__/components/ProductionLocationInfo.test.js
src/react/src/components/Contribute/ProductionLocationInfo.jsx
src/react/src/util/styles.js

Fix [OSDEV-1814]( https://opensupplyhub.atlassian.net/browse/OSDEV-1814)
1. Replaced arrow dropdown icon by toggle switch button in production location info page.
2. When go to update flow (`contribute/single-location/{os_id}/info/`), Update button is active by default. 
3. _Additional data_ section hidden by default for update and create new production location flows.
4. When _Additional dat_a section expanded, update button can be disabled due to invalid incoming fields (such as number of workers range that starts from zero).
5.  When _Additional data_ section expanded, pre-filled values will be send to the server along with name, country and address values. This applies event if user just expand _Additional data_ section and don't input any data from their side.
[OSDEV-1814]: …

[OSDEV-1814] Add toggle switch for Additional data section

---

doc/release/RELEASE-NOTES.md
src/react/src/components/Contribute/ContributeProductionLocation.jsx
src/react/src/components/Contribute/ProductionLocationInfo.jsx
src/react/src/components/Contribute/SearchByNameAndAddressResult.jsx
src/react/src/components/Contribute/SearchByOsIdResult.jsx
src/react/src/util/hooks.js

[OSDEV-1789](https://opensupplyhub.atlassian.net/browse/OSDEV-1789) **SLC. "Search results" scrolls from the bottom**
- Fixed an issue where the scroll position was not resetting to the top when navigating through SLC workflow pages.
[OSDEV-1789]: https://opensupplyhub.atlassian.net/browse/OSDEV-1789?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OSDEV-1789] SLC. "Search results" scrolls from the bottom

---

doc/release/RELEASE-NOTES.md
src/react/src/__tests__/components/SearchByOsIdTab.test.js
src/react/src/components/Contribute/SearchByOsIdTab.jsx

[OSDEV-1838](https://opensupplyhub.atlassian.net/browse/OSDEV-1838) - SLC. Fix search by OS ID that contains slash.
This PR fixes an issue where the router redirected to an unsupported page when the OS ID contained a forward slash. The issue was resolved by encoding the OS ID value using the `encodeURIComponent()` function before passing it as a URL parameter.
[OSDEV-1838]: https://opensupplyhub.atlassian.net/browse/OSDEV-1838?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OSDEV-1838] Fix search by OS ID that contains slash or other special characters.

---

deployment/environments/terraform-preprod.tfvars
deployment/environments/terraform-production.tfvars
doc/release/RELEASE-NOTES.md

[OSDEV-1832](https://opensupplyhub.atlassian.net/browse/OSDEV-1832) **Increase the memory allocation for the DedupeHub in Terraform configuration for Pre-Prod & Production**
- Increased the memory allocation for the `DedupeHub` container from `12GB` to `16GB` in terraform deployment configuration to address memory overload issues during facility reindexing for `Production` & `Pre-Production` environments.
[OSDEV-1832]: https://opensupplyhub.atlassian.net/browse/OSDEV-1832?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OSDEV-1832] Increase the memory allocation for the DedupeHub in Terraform configuration for Pre-Prod & Production

---

deployment/terraform/anonymized_database_dump_scheduled_task/docker/dump.sh
doc/release/RELEASE-NOTES.md

In this pull request, we fix the snapshot status checking procedure. This will prevent a crash when trying to restore a database from an inaccessible snapshot.

Wait for snapshot get status - available

---

doc/release/RELEASE-NOTES.md
src/react/src/components/Contribute/ProductionLocationDialog.jsx

[OSDEV-1831](https://opensupplyhub.atlassian.net/browse/OSDEV-1831) - SLC UAT Bug - Update copy in "Thank you for adding data" pop-up (new OS ID use case).
This PR updates copies of tooltips on the “Thank you for adding data” pop-up. The texts vary depending on the claim status for a particular location.
[OSDEV-1831]: https://opensupplyhub.atlassian.net/browse/OSDEV-1831?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OSDEV-1831] Update text of tooltip on the "Thank you for adding data" pop-up base on the claim status of the production location.

---

doc/release/RELEASE-NOTES.md
src/django/api/processing.py
src/django/api/tests/test_facility_create_api.py

Fix [OSDEV-1769](https://opensupplyhub.atlassian.net/browse/OSDEV-1769)
Fixed the response for potential matches for POST `api/facilities/?create=true`: applied an array of potential matches instead of returning a single potential match.
[OSDEV-1769]: https://opensupplyhub.atlassian.net/browse/OSDEV-1769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OSDEV-1769] Refactor potential matches response for POST api/facilities/?create=true

---

doc/release/RELEASE-NOTES.md
src/react/src/util/constants.jsx

[OSDEV-1867](https://opensupplyhub.atlassian.net/browse/OSDEV-1867) **SLC. Update Messy Data link to data cleaning service splash page**
- Updated the 'Messy Data' link on the `Contribute` page and `List Upload` page to direct users to the `Data Cleaning Service splash` page instead of the old `Preparing Data` page.
[OSDEV-1867]: https://opensupplyhub.atlassian.net/browse/OSDEV-1867?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OSDEV-1867] SLC. Update Messy Data link to data cleaning service splash page

---

doc/release/RELEASE-NOTES.md
src/react/src/__tests__/components/ProductionLocationDialog.test.js
src/react/src/__tests__/components/RejectModerationEventDialog.test.js
src/react/src/components/Contribute/ProductionLocationDialog.jsx

Follow-up fix for [OSDEV-1831](https://opensupplyhub.atlassian.net/browse/OSDEV-1831)
Changed tooltip text for pending badge if existing production location has pending claim status or has been claimed already.
[OSDEV-1831]: https://opensupplyhub.atlassian.net/browse/OSDEV-1831?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OSDEV-1831] Fix tooltip message for pending badge

---

doc/release/RELEASE-NOTES.md
src/react/src/__tests__/components/ProductionLocationInfo.test.js
src/react/src/components/Contribute/ProductionLocationInfo.jsx

[OSDEV-1830](https://opensupplyhub.atlassian.net/browse/OSDEV-1830) **SLC UAT Bug - Drop down menus under Additional information section do not show all available options**
- Updated implementation to input any values for Location Type and Processing Type, except when the sector is Apparel—in that case, enforce taxonomy filters.
- Updated UI tests for ProductionLocationInfo component to covered recent changes.
[OSDEV-1830]: https://opensupplyhub.atlassian.net/browse/OSDEV-1830?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OSDEV-1830] SLC UAT Bug - Drop down menus under Additional information section do not show all available options

---

doc/release/RELEASE-NOTES.md
docker-compose.yml

**[OSDEV-1899](https://opensupplyhub.atlassian.net/browse/OSDEV-1899) Kafka/Zookeeper Images startup issue**
- Switched from using the `latest` tags to static versions for both `bitnami/kafka` and `bitnami/zookeeper`, which resolved compatibility issues during local & CI setup. Using pinned versions ensures stability and prevents unexpected behavior from upstream image changes.
[OSDEV-1899]: https://opensupplyhub.atlassian.net/browse/OSDEV-1899?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OSDEV-1899] Kafka/Zookeeper Images startup issue

---

.github/workflows/destroy.yml
deployment/delete_lambda
doc/release/RELEASE-NOTES.md

Delete Lambda@Edge function before deleting infrastructure. These changes are necessary so that infrastructure can be deleted using terraform without receiving an error about a problem deleting a replicated function.

[OSDEV-1886] Delete Lambda@Edge function before destroying environment

---

doc/release/RELEASE-NOTES.md
src/react/src/components/Contribute.jsx
src/react/src/util/constants.jsx

[OSDEV-1904](https://opensupplyhub.atlassian.net/browse/OSDEV-1904) - The `step-by step` instructions link on the List upload page has been updated to `/resources/preparing-data`.
[OSDEV-1904]: https://opensupplyhub.atlassian.net/browse/OSDEV-1904?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OSDEV-1904] Update the  instructions link on the List upload page.

---

doc/release/RELEASE-NOTES.md
src/django/api/constants.py
src/django/api/serializers/v1/opensearch_common_validators/coordinates_validator.py
src/django/api/serializers/v1/opensearch_common_validators/geo_polygon_validator.py
src/django/api/serializers/v1/production_locations_serializer.py
src/django/api/tests/test_production_locations_query_builder.py
src/django/api/tests/test_v1_utils.py
src/django/api/views/v1/opensearch_query_builder/opensearch_query_director.py
src/django/api/views/v1/opensearch_query_builder/production_locations_query_builder.py
src/django/api/views/v1/parameters_list.py
src/django/api/views/v1/utils.py
src/tests/v1/test_production_locations.py

Fix [OSDEV-1201](https://opensupplyhub.atlassian.net/browse/OSDEV-1201)
Added support of `geo_polygon` parameter for GET `v1/production-locations` endpoint.
[OSDEV-1201]: https://opensupplyhub.atlassian.net/browse/OSDEV-1201?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OSDEV-1201] Added support of geo_polygon parameter for GET v1/production-locations endpoint

---

.github/workflows/destroy.yml
deployment/delete_lambda

Pre-initialization of a variable.
The sequence of steps in the pipeline has been corrected.

[OSDEV-1886] Pre-initialization of a variable

---

doc/release/RELEASE-NOTES.md
src/react/src/components/Contribute/ProductionLocationInfo.jsx

[OSDEV-1943](https://opensupplyhub.atlassian.net/browse/OSDEV-1943) - Fixed flickering behavior when opening the SLC form to contribute to an existing production location by marking fields as touched if they match the fetched data, ensuring smoother UI during re-renders.
[OSDEV-1943]: https://opensupplyhub.atlassian.net/browse/OSDEV-1943?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OSDEV-1943] Eliminate brief red border flicker on pre-filled fields in the SLC form .

---

deployment/terraform/vanta-iam-role/vanta-readonly-role.tf
deployment/terraform/vanta-iam-role/variables.tf
deployment/terraform/vanta.tf
deployment/terraform/variables.tf
doc/release/RELEASE-NOTES.md

The changes in this pull request create an IAM role in the AWS account to enable integration with the Vanta auditor.
This integration is required for SOC 2 certification.
Since we have two AWS accounts, the changes apply only to the production and testing environments.

[OSDEV-1935] Grant Vanta auditor access to AWS account

---

doc/release/RELEASE-NOTES.md
src/django/api/tests/test_production_locations_query_builder.py
src/django/api/views/v1/opensearch_query_builder/opensearch_query_builder.py
src/django/api/views/v1/opensearch_query_builder/opensearch_query_director.py
src/react/src/components/Dashboard/DashboardContributionRecord.jsx
src/react/src/reducers/DashboardContributionRecordReducer.js
src/tests/opensearch/test_opensearch.py

[OSDEV-1914](https://opensupplyhub.atlassian.net/browse/OSDEV-1914)
* Fixed an issue with fuzzy search on fields containing long text. Replaced the `match` query with `match_phrase` (with a configurable `slop` parameter) for such cases to improve accuracy for the GET `/api/v1/production-locations/` endpoint.
* Replaced regular text with a toast component to display server errors when fetching potential matches on the Contribution Record page of the Moderation queue dashboard.
Error UI example:
[OSDEV-1914]: https://opensupplyhub.atlassian.net/browse/OSDEV-1914?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OSDEV-1914] Add match_phrase query support for fields with long string values

---

deployment/delete_lambda
doc/release/RELEASE-NOTES.md

Adding the `set +e` command is necessary to ensure that the script does not terminate on an error, allowing us to handle the exit code of the Lambda function deletion command manually. This is especially useful in cases where the function might already be deleted or doesn't exist — the `aws lambda delete-function` command would return an error, but with `set +e`, we can catch that error and decide how to proceed.

[OSDEV-1886] Disable script crash when getting exit code 254 from aws cli when deleting Lambda@Edge function

---

src/react/src/util/apiRequest.js

[OSDEV-1895](https://opensupplyhub.atlassian.net/browse/OSDEV-1895) **FIX: [RBA Pen Test] Address pen test results of Cookies without HTTP-only**
- Fixed issue when in axios headers stored old csrf token but new valid csrf token was already generated and saved in local storage.
[OSDEV-1895]: https://opensupplyhub.atlassian.net/browse/OSDEV-1895?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OSDEV-1895] FIX: Address pen test results of Cookies without HTTP-only

---

src/django/contricleaner/lib/serializers/row_serializers/row_additional_ids_serializer.py
src/django/contricleaner/tests/test_row_additional_ids_serializer.py

[OSDEV-1926](https://opensupplyhub.atlassian.net/browse/OSDEV-1926) - [RBA Data Model] Allow submission of additional identifiers through the API.
In this PR was modified the error message for the invalid `duns_id` value.
[OSDEV-1926]: https://opensupplyhub.atlassian.net/browse/OSDEV-1926?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OSDEV-1926] Modify the error message for the invalid `duns_id`.

---

doc/release/RELEASE-NOTES.md

Removed template text from release notes before the `release 2.4.0`.

Remove template text from release notes before the release 2.4

---

.github/workflows/deploy_to_aws.yml
doc/release/RELEASE-NOTES.md

Updated the `Deploy to AWS` GitHub workflow to rely on the required `deploy-env` input instead of inferring the `environment` from the tag name. Previously, this approach was necessary because the `[Release] Deploy` workflow did not trigger `Deploy to AWS` via the API with the specified `environment` - it only created a tag that triggered the workflow automatically. With the latest changes, the `environment` is now explicitly passed in the `[Release] Deploy` workflow. It has also been confirmed that no branch or input combination can result in an undefined `environment`. As a result, the fallback to `None` for the `environment` value was removed from the `Deploy to AWS` workflow.
Tested by running `[Release] Deploy` workflow:
1. https://github.com/opensupplyhub/open-supply-hub/actions/runs …

Removed unnecessary tag check and assignment of None in the "Deploy to AWS" GitHub workflow

---

doc/release/RELEASE-NOTES.md
src/react/src/__tests__/components/Footer.test.js
src/react/src/components/AddLocationData.jsx
src/react/src/components/Navbar/InternationalMenu.jsx
src/react/src/components/Navbar/MobileInternationalMenu.jsx
src/react/src/util/constants.jsx

[OSDEV-1998](https://opensupplyhub.atlassian.net/browse/OSDEV-1998) - [FE] Update OS Hub platform header & footer.
Changes made:
- Added an additional "Data Cleaning Service" subheader to the "How It Works" > "Premium Features" section.
- Updated the list of supported languages/countries under the "globe" icon (added support for Chinese and changed the order).
- Removed the Twitter icon from the social media icons/links in the footer.
[OSDEV-1998]: https://opensupplyhub.atlassian.net/browse/OSDEV-1998?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OSDEV-1998] Update OS Hub platform header and footer.

---

doc/release/RELEASE-NOTES.md
src/django/api/moderation_event_actions/approval/event_approval_template.py
src/django/api/moderation_event_actions/approval/update_production_location.py
src/django/api/tests/test_facility_history_endpoint.py
src/django/api/tests/test_moderation_events_update_production_location.py
src/django/api/views/facility/facilities_view_set.py
src/django/api/views/facility/facility_match_view_set.py
src/django/api/views/v1/moderation_events.py

[OSDEV-1981](https://opensupplyhub.atlassian.net/browse/OSDEV-1981) **GET v1/production-locations/{os_id}/ endpoint doesn't return additional identifiers "duns_id", "lei_id", "rba_id"**
- Fixed an issue where the `updated_at` field in the `api_facility` table was not modified when related dependency data changed, resulting in outdated or invalid data being stored in `OpenSearch`.
- Updated unit test case to cover changes with `api_facility` field `updated_at`.
[OSDEV-1981]: https://opensupplyhub.atlassian.net/browse/OSDEV-1981?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OSDEV-1981] GET v1/production-locations/{os_id}/ endpoint doesn't return additional identifiers "duns_id", "lei_id", "rba_id"

---

.github/workflows/deploy_to_aws.yml
deployment/terraform/vpn-ec2.tf
doc/release/RELEASE-NOTES.md

Pre-code freeze PR for release `v.2.5.0`
1.  Set EC2 VPN to RBA instance only.
2. No longer refer to the test PR https://github.com/opensupplyhub/ci-deployment/pull/33 while Deploy to AWS
3. Remove empty sections from Release notes.
4. Disabled open access to the WireGuard WebUI.

Refinde readme, set EC2 VPN to RBA only

---

deployment/environments/terraform-development.tfvars
deployment/environments/terraform-preprod.tfvars
deployment/environments/terraform-production.tfvars
deployment/environments/terraform-rba.tfvars
deployment/environments/terraform-staging.tfvars
deployment/environments/terraform-test.tfvars

Removed `waf_enabled` variables from this repo and introduce them in **ci-deployment** (See: https://github.com/opensupplyhub/ci-deployment/pull/37)

[OSDEV-2035] Remove waf_enabled variables for all envs

---

deployment/terraform/batch.tf
src/django/api/management/commands/direct_data_load.py

Change the name from `__mark_row` to `_mark_row` because the script was failing during the execution. Also re-thrown the error from database insert instead of just breaking the loop.

[OSDEV-1951] Fix the issue when script can't mark rows red

---

deployment/environments/terraform-development.tfvars
deployment/environments/terraform-preprod.tfvars
deployment/environments/terraform-production.tfvars
deployment/environments/terraform-rba.tfvars
deployment/environments/terraform-staging.tfvars
deployment/environments/terraform-test.tfvars
deployment/terraform/container_service.tf
deployment/terraform/job-definitions/default.json
deployment/terraform/job-definitions/direct_data_load.json
deployment/terraform/job-definitions/export_csv.json
deployment/terraform/job-definitions/notifications.json
deployment/terraform/task-definitions/app.json
deployment/terraform/task-definitions/app_cli.json
deployment/terraform/task-definitions/app_dd.json
deployment/terraform/variables.tf
src/dedupe-hub/api/app/config.py
src/dedupe-hub/api/app/database/signals/origin_source.py
src/django/api/fixtures/contributors.json
src/django/api/fixtures/facilities_index.json
src/django/api/fixtures/facility_lists.json
src/django/api/fixtures/sources.json
src/django/api/fixtures/users.json

[OSDEV-2019](https://opensupplyhub.atlassian.net/browse/OSDEV-2019) **OS Hub DB. Add source column to tables for tracking origin of records**
- Added origin_source field to fixtures data.
- Fixed issue with INSTANCE_SOURCE for Dedupe Hub if no environment variable is provided
- Updated terraform variables.
[OSDEV-2019]: https://opensupplyhub.atlassian.net/browse/OSDEV-2019?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FIX-2: [OSDEV-2019] OS Hub DB. Add source column to tables for tracking origin of records

---

doc/release/RELEASE-NOTES.md
src/logstash/scripts/production_locations/location_type.rb
src/logstash/scripts/production_locations/processing_type.rb

[[OSDEV-2032](https://opensupplyhub.atlassian.net/browse/OSDEV-2038)]
Fixed the incorrect indexing of the location type in the production locations OpenSearch index. Previously, it was incorrectly taking the processing type value as the location type — using the fourth item in the `matched_values` array instead of the third, which contains the location type. Also, updated the Logstash filters for both processing type and location type to return only unique values and write them to the production locations OpenSearch index.
[OSDEV-2032]: https://opensupplyhub.atlassian.net/browse/OSDEV-2032?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OSDEV-2032] Fixed the incorrect indexing of the location type in the production locations OpenSearch index

---

doc/release/RELEASE-NOTES.md
src/react/src/actions/downloadLimit.js
src/react/src/components/DownloadFacilitiesButton.jsx
src/react/src/reducers/DownloadLimitReducer.js

**[Release Bug] [OSDEV-2107](https://opensupplyhub.atlassian.net/browse/OSDEV-2107) Search button redirects user to Stripe Checkout page instead of search result**
- Fixed an issue where navigating back from the Stripe Checkout page using the browser’s back button caused the search button to repeatedly redirect to Stripe Checkout.
[OSDEV-2107]: https://opensupplyhub.atlassian.net/browse/OSDEV-2107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Release Bug] [OSDEV-2107] Search button redirects user to Stripe Checkout page instead of search result

---

deployment/environments/terraform-development.tfvars
deployment/environments/terraform-preprod.tfvars
deployment/environments/terraform-production.tfvars
deployment/environments/terraform-rba.tfvars
deployment/environments/terraform-staging.tfvars
deployment/environments/terraform-test.tfvars
deployment/terraform/variables.tf
deployment/terraform/vpn-ec2.tf
doc/release/RELEASE-NOTES.md

[[OSDEV-2123](https://opensupplyhub.atlassian.net/browse/OSDEV-2123)]
Updated VPN EC2 instance configuration to use a specific Amazon Linux 2023 AMI (ami-0940c95b23a1f7cac) instead of dynamically selecting the most recent AMI. This change ensures consistent AMI usage across deployments and prevents unnecessary reboots of the VPN server that could result in loss of VPN access through WireGuard.
[OSDEV-2123]: https://opensupplyhub.atlassian.net/browse/OSDEV-2123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Backmerge][OSDEV-2123] Updated VPN EC2 instance configuration to use a specific AMI

---

doc/release/RELEASE-NOTES.md
src/django/Dockerfile
src/django/requirements.txt

**[OSDEV-2083](https://opensupplyhub.atlassian.net/browse/OSDEV-2083) Update python and OpenSearch client versions**
- Updated Python version from `3.7` to `3.8` to support higher OpenSearch client version with necessary features.
- Added system dependencies: `libmemcached-dev`, `zlib1g-dev` to support building C-based packages like `pylibmc`.
- Package `pytz` upgraded from `2018.7` → `2023.3` to include up-to-date and stable timezone data.
- Package `requests` upgraded from `2.31.0` → `2.32.4` for improved security and compatibility.
- Package `opensearch-py` upgraded from `2.5.0` → `2.8.0` to enable hybrid search.
[OSDEV-2083]: https://opensupplyhub.atlassian.net/browse/OSDEV-2083?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OSDEV-2083] Update python and OpenSearch client versions

---

doc/release/RELEASE-NOTES.md
src/anon-tools/do_restore.sh

Enhanced the `./src/anon-tools/do_restore.sh` script to use more precise filtering when looking up the bastion host, improving reliability and reducing potential for incorrect host selection. The *bastion* filter now ensures that only an instance tagged with both the correct environment and the specific "Bastion" name is selected.
_Note: The changes have been successfully tested in the RBA environment, where multiple EC2 instances are running._

Enhanced the ./src/anon-tools/do_restore.sh script to use more precise filtering when looking up the bastion host

---

src/django/api/services/facilities_download_service.py
src/django/api/tests/test_facilities_download_viewset.py

**[Quickfix-2.12.0] [OSDEV-2137](https://opensupplyhub.atlassian.net/browse/OSDEV-2137) Fix incorrect next page for multiple query param in Facilities Download endpoint**
- Quick fix for multiple values for filter params like countries when build next or previous page
- Added unit tests
[OSDEV-2137]: https://opensupplyhub.atlassian.net/browse/OSDEV-2137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Quickfix-2.12.0][OSDEV-2137] Fix incorrect next page for multiple query param in Facilities Download endpoint 

---

src/django/api/services/facilities_download_service.py
src/django/api/tests/test_facilities_download_viewset.py

**[OSDEV-2137](https://opensupplyhub.atlassian.net/browse/OSDEV-2137) Fix incorrect next page for multiple query param in Facilities Download endpoint**
- Fix for multiple values for filter params like countries when build next or previous page
- Added unit tests
[OSDEV-2137]: https://opensupplyhub.atlassian.net/browse/OSDEV-2137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OSDEV-2137] Fix incorrect next page for multiple query param in Facilities Download endpoint 

---

deployment/environments/terraform-rba.tfvars
doc/release/RELEASE-NOTES.md

[Follow-up] [OSDEV-2077](https://opensupplyhub.atlassian.net/browse/OSDEV-2077) - Disabled the RBA synchronization script trigger via the `db_sync_enabled` Terraform variable due to the temporary unnecessity of synchronization.
[OSDEV-2077]: https://opensupplyhub.atlassian.net/browse/OSDEV-2077?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Quickfix-v.2.12][OSDEV-2077] Disabled RBA sync script trigger via db_sync_enabled TF variable

---

deployment/terraform/database-private-link-provider/variables.tf
doc/release/RELEASE-NOTES.md
src/django/api/management/commands/sync_databases.py

[Follow-up]  [OSDEV-2029](https://opensupplyhub.atlassian.net/browse/OSDEV-2029) - Enhanced `sync_databases.py` script (which synchronizes RBA and Production(OS Hub) databases) with improved resilience: implemented checkpoint-based progress saving after each chunk (default 1000 records) instead of only at the end of processing; added configurable connection refresh mechanism (default 15 hours) to prevent RDS Proxy 24-hour timeout during long-running syncs; implemented session-based processing with break-and-resume approach to safely refresh database connections without closing active cursors. 
[OSDEV-2029]: https://opensupplyhub.atlassian.net/browse/OSDEV-2029?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Backmerge][OSDEV-2029] Improved database sync resilience with checkpoints and connection refresh

---

doc/release/RELEASE-NOTES.md
src/django/api/management/commands/sync_databases.py

[Follow-up] [OSDEV-2029](https://opensupplyhub.atlassian.net/browse/OSDEV-2029) - Fixed database connection timeout in the Django `sync_databases` command by implementing global session time tracking. Previously, session time was reset when switching between models, causing the connection to exceed the 24-hour RDS Proxy timeout. Now session time persists across all models and only resets after actual connection refreshes.
[OSDEV-2029]: https://opensupplyhub.atlassian.net/browse/OSDEV-2029?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OSDEV-2029] Fixed database connection timeout in the Django `sync_databases` command by implementing global session time tracking.
