opensupplyhub/open-supply-hub

- README.md
- docker-compose.yml
- Combine DedupeHub settings for the docker-compose.yml with the main one.
- Update Readme file.
> [OSDEV-759] Fix docker-compose.yml

- src/django/api/tests/test_api_limit.py
[OSDEV-729](https://opensupplyhub.atlassian.net/browse/OSDEV-729) Add missing tests (Django)
- added missing tests from previous repo related to APILimitTest
> [OSDEV-729] Add missing tests (Django)

- .github/workflows/code_quality.yml
- doc/RELEASE-NOTES.md
Increase `minimum-ratio:` to 1
This solution isn't the best as it allows to decrease coverate for 1% what's too much, but this is munimal value
> [OSDEV 829] make possibility to push code with less than  1% diff in coverage from main

- .github/workflows/deploy_to_aws.yml
- .github/workflows/destroy.yml
Fid deleting environment expression
> Fix issue when environment on main is selected incorrectly

- src/app/src/components/FacilityListItemsConfirmationTableRow.jsx
[OSDEV-219](https://opensupplyhub.atlassian.net/browse/OSDEV-219) Add follow-up fix of conditional rendering of the select action field
> [OSDEV-219] - Add conditional rendering for select action

- .github/workflows/deploy_to_aws.yml
Fix automatic deployment to Development environment when **main** branch updated.
> Fix automatic deployment to Development environment 

- .github/workflows/deploy_to_aws.yml
Add possibility to select 'Staging' and 'Production' when manually start deploy
> Add 'Staging' and 'Production' to selection

- .github/workflows/deploy_to_aws.yml
Don use contri-cleaner service for uploading facilities
> Disable the switch in routing to the ContriCleaner

- doc/release/RELEASE-NOTES.md
- src/app/src/components/FilterSidebarSearchTab.jsx
[OSDEV-716](https://opensupplyhub.atlassian.net/browse/OSDEV-716)
* The refresh icon has been made visible.
> [OSDEV-716] Search. Lost refresh icon.

- doc/release/RELEASE-NOTES.md
[OSDEV-903](https://opensupplyhub.atlassian.net/browse/OSDEV-903) Add records to the doc/release/RELEASE-NOTES.md that describe implemented changes in the issue OSDEV-702
> [OSDEV-903] Add details to doc/release/RELEASE-NOTES.md after changes related to OSDEV-702

- doc/release/RELEASE-NOTES.md
- src/app/src/util/util.js
[OSDEV-917](https://opensupplyhub.atlassian.net/browse/OSDEV-917)
Update the order of the settings tabs.
* `NON-admin` user sees: My Facility / My Lists / Settings / Logout 
* `Admin` user sees: Dashboard / My Facility / My Lists / Settings / Logout
> [OSDEV-917] My Account Menu. Update order of the settings tabs.

- src/django/oar/settings.py
Add the Development environment to ECSMANAGE_ENVIRONMENTS
Make possible to run Django commands in ecs
> [OSDEV-877] Add development environment

- src/django/countries/tests/test_country_code_parser.py
Add additional tests for the `get_country_code` function that helps to cover code by tests in `countries` by 100%
> Add additional tests for get_country_code function

- src/dedupe-hub/api/requirements.txt
[OSDEV-911](https://opensupplyhub.atlassian.net/browse/OSDEV-911) Add code quality pipelines for dedupe-hub | Part 1
- Added coverage package to Dedupe Hub
> [OSDEV-911] Add code quality pipelines for dedupe-hub | Part 1

- .gitignore
- docker-compose.yml
[OSDEV-911](https://opensupplyhub.atlassian.net/browse/OSDEV-911) Add code quality pipelines for dedupe-hub | Part 3
- Added volume to copy coverage result to code source in main branch
> [OSDEV-911] Add code quality pipelines for dedupe-hub | Part 3

- .github/workflows/db_apply_anonimized.yml
- .github/workflows/db_retrieve_anonymized.yml
- doc/release/RELEASE-NOTES.md
[OSDEV-859](https://opensupplyhub.atlassian.net/browse/OSDEV-859)
> [OSDEV-859] Add empty "save" and "apply" anonymised db workflows

- src/dedupe-hub/api/tests/test_clean.py
[OSDEV-911](https://opensupplyhub.atlassian.net/browse/OSDEV-911) Add code quality pipelines for dedupe-hub | Part 4
- added simple test to Dedupe Hub
> [OSDEV-911] Add code quality pipelines for dedupe-hub | Part 4

- src/app/src/util/util.js
- src/django/api/matching.py
- src/django/api/middleware.py
- src/django/api/processing.py
- src/django/api/views/facility/facility_list_view_set.py
- src/django/oar/rollbar.py
Hotfix [OSDEV-802](https://opensupplyhub.atlassian.net/browse/OSDEV-802)
Rollbar:
1. Add custom fingerprint for Rollbar send error function
2. Pass error object to `report_error_to_rollbar()` in Django app
3. TODO - apply these Rollbar settings in OSHub project:
```
[
{
"condition":{
"contains":"User",
"path":"body.trace.exception.message"
},
"fingerprint":"{{custom.fingerprint}}",
"action":{
"type":"merge"
}
}
]
```
> Hotfix 1.10.1 osdev 802

- src/app/src/util/util.js
- src/django/api/matching.py
- src/django/api/middleware.py
- src/django/api/processing.py
- src/django/api/views/facility/facility_list_view_set.py
- src/django/oar/rollbar.py
Backmerge of https://github.com/opensupplyhub/open-supply-hub/pull/109
> [OSDEV 802] hotfix backmerge

- .github/workflows/deploy_to_aws.yml
- deployment/environments/terraform-test.tfvars
- deployment/terraform/task-definitions/app_dd.json
[OSDEV-953](https://opensupplyhub.atlassian.net/browse/OSDEV-953) Increase configuration for test environment
- Updated Dedupe Hub config .tfvars file for **Test**:
* 4 CPU
* 8 GB Memory
- Added job to update Dedupe Hub service with new Image
> [OSDEV-953] Increase configuration for test environment

- src/app/src/components/FacilityListItemsTable.jsx
- src/app/src/components/Filters/StyledSelect.jsx
Backmerge of https://github.com/opensupplyhub/open-supply-hub/pull/104
> [OSDEV-954] Scroll bar isn't available while scrolling in search fields

- src/app/src/util/util.js
- src/django/oar/rollbar.py
Hotfix for [OSDEV-802](https://opensupplyhub.atlassian.net/browse/OSDEV-802)
> Update rollbar fingerprint

- src/app/src/util/util.js
- src/django/oar/rollbar.py
Backmerge of https://github.com/opensupplyhub/open-supply-hub/pull/114
> Update rollbar fingerprint (#114)

- .github/workflows/db_retrieve_anonymized.yml
- .github/workflows/deploy_to_aws.yml
- deployment/run_kafka_task
- deployment/terraform/container_service.tf
- deployment/terraform/dns.tf
- deployment/terraform/servicediscovery-drain.sh
* Creates kafka topic automatically
* Make Public IP for Kafka tool task enabled
* use commit sha as Kafka-tools image tag
> [OSDEV-852] Create kafka topic automatically

- deployment/run_kafka_task
- deployment/terraform/container_service.tf
- Make Public IP for Kafka tool task enabled
- use commit sha as Kafka-tools image tag
> [OSDEV-852] Make Kafka Run Task script to use public IP

- .github/workflows/deploy_to_aws.yml
- deployment/run_cli_task
* Create kafka topic
* Update services
* Run migrations via run_cli_task script
[OSDEV-874](https://opensupplyhub.atlassian.net/browse/OSDEV-874)
> [OSDEV-874] Change order of deploy

- src/dedupe-hub/api/app/main.py
- src/dedupe-hub/api/app/matching/matcher/gazeteer/gazetteer_cache.py
https://github.com/opensupplyhub/open-supply-hub/pull/123 -> for hotfix release
> [Hotfix v1.10.1] Remove passing exception to try_reporting_error_to_rollbar

- doc/release/RELEASE-NOTES.md
- src/app/src/components/FacilityListItemsErrorTableRow.jsx
- src/app/src/util/styles.js
- src/django/api/views/facility/facility_list_view_set.py
- src/django/contricleaner/lib/parsers/file_parser.py
- src/django/contricleaner/lib/parsers/source_parser_csv.py
- src/django/contricleaner/lib/parsers/source_parser_xlsx.py
- src/django/contricleaner/tests/test_source_parser_csv.py
- src/django/contricleaner/tests/test_source_parser_xlsx.py
Fix [[OSDEV-979](https://opensupplyhub.atlassian.net/browse/OSDEV-979)] Upload: List are receiving an error at the parsing phase during upload
> Hotfix [OSDEV-979] Upload: List are receiving an error at the parsing phase during upload

- doc/release/RELEASE-NOTES.md
- src/dedupe-hub/api/app/main.py
- src/dedupe-hub/api/app/matching/matcher/exact/exact_matcher.py
- src/dedupe-hub/api/app/matching/matcher/gazeteer/gazetteer_cache.py
- src/dedupe-hub/api/app/matching/matcher/gazeteer/gazetteer_matcher.py
- src/dedupe-hub/api/app/matching/process_match.py
- src/django/api/management/commands/batch_process.py
- src/django/api/processing.py
- src/django/api/views/facility/facilities_view_set.py
- src/django/api/views/facility/facility_list_view_set.py
[OSDEV-923](https://opensupplyhub.atlassian.net/browse/OSDEV-923) Add more logs around API and list uploads
- Added additional logs with steps & details data to API upload
- Added additional logs with steps & details data to List upload
- Added additional logs with steps & details data to Dedupe Hub match processing
> [OSDEV-923] Add more logs around API and list uploads

- src/django/contricleaner/lib/serializers/row_serializers/row_composite_serializer.py
- src/django/contricleaner/tests/test_row_composite_serializer.py
[OSDEV-660](https://opensupplyhub.atlassian.net/browse/OSDEV-660) - Fix minor issue with trimming spaces before commas and duplicated spaces.
> OSDEV-660 - Apply removing spaces before commas

- deployment/terraform/config.tf
- deployment/terraform/locals.tf
- doc/release/RELEASE-NOTES.md
Make Environment and Project tag to be applied to all resources by default.
[OSDEV-805](https://opensupplyhub.atlassian.net/browse/OSDEV-805)
> [OSDEV-805] Setting default tags on resources

- doc/release/RELEASE-NOTES.md
- src/django/api/facility_actions/create_facility.py
- src/django/api/facility_actions/processing_facility.py
- src/django/api/views/facility/facilities_view_set.py
[OSDEV-1000](https://opensupplyhub.atlassian.net/browse/OSDEV-1000) -  Move facility processing received from API to a separate class `ProcessingFacility`.
The functionality of processing a new facility, which was previously in `facilities_view_set.py`, has been moved to `processing_facility.py.` 
This marks the initial step in implementing a single class responsible for managing the processing of new facilities from both API requests and list uploads.
> [OSDEV-1000] Move facility processing received from api to a separate class

- doc/release/RELEASE-NOTES.md
Creates new section in release-notes.md
> Add section dedicated to release 1.12.0

- doc/release/RELEASE-NOTES.md
- src/app/src/components/FacilityDetailsClaimFlag.jsx
[OSDEV-945](https://opensupplyhub.atlassian.net/browse/OSDEV-945) **Facility Claim. Update text of claim link on profile.**
- Updated text from _"Owners or managers can claim this facility"_ to _"I want to claim this site"_
> [OSDEV-945] Facility Claim. Update text of claim link on profile. 

- src/dedupe-hub/api/Dockerfile
- src/dedupe-hub/api/requirements.txt
Reverts opensupplyhub/open-supply-hub#102
> Revert "Bump the Python version to 3.8"

- src/dedupe-hub/api/Dockerfile
- src/dedupe-hub/api/requirements.txt
Reverts https://github.com/opensupplyhub/open-supply-hub/pull/102
> Revert Bump the Python version to 3.8

- doc/release/RELEASE-NOTES.md
- src/django/api/templates/mail/claim_facility_denial_body.html
- src/django/api/templates/mail/claim_facility_revocation_body.html
- src/react/src/components/ClaimFacilityVerificationInfoStep.jsx
- src/react/src/util/util.js
Fix https://opensupplyhub.atlassian.net/browse/OSDEV-1052
> [Osdev 1052] Replace data@opensupplyhub by claims@opensupplyhub in the Frontend

- .github/workflows/deploy_to_aws.yml
* use `ubuntu-latest` instead of `self-hosted`
> Use Github Runner for update_services step

- doc/release/RELEASE-NOTES.md
- src/django/api/templates/mail/claim_facility_denial_body.html
- src/django/api/templates/mail/claim_facility_revocation_body.html
- src/react/src/components/ClaimFacilityVerificationInfoStep.jsx
- src/react/src/util/util.js
Backmerge of https://github.com/opensupplyhub/open-supply-hub/pull/203
> Backmerge - [Osdev 1052] Replace data@opensupplyhub by claims@opensupplyhub

- src/anon-tools/do_restore.sh
* ignore results of pg_restore as it always fails even when db restored correctly so that pipelines proceeds with further steps
> Ignore errors on restore

- deployment/terraform/database_anonymizer_sheduled_task/docker/anonymize_script.sql
- doc/release/RELEASE-NOTES.md
- src/anon-tools/anon.sql
- src/anon-tools/do_dump.sh
Fix [OSDEV-1056](https://opensupplyhub.atlassian.net/browse/OSDEV-1056)
> [OSDEV-1056] Replace opensupplyhub.com by opensupplyhub.org for proper anonymization

- doc/release/RELEASE-NOTES.md
- src/react/src/components/CookiePreferencesText.jsx
[OSDEV-922](https://opensupplyhub.atlassian.net/browse/OSDEV-922) Consent Message. Update wording of consent opt in message on Open Supply Hub.  A user who verifies Open Supply Hub for the first time can see the updated message.
> [OSDEV-922] Consent Message. Update wording of consent opt in message on Open Supply Hub.

- doc/release/RELEASE-NOTES.md
- src/django/api/extended_fields.py
- src/django/api/tests/test_index_facilities.py
Fix [OSDEV-1022](https://opensupplyhub.atlassian.net/browse/OSDEV-1022)
> [Osdev 1022] Claims user unable to update facility claim

- doc/release/RELEASE-NOTES.md
- src/react/package.json
- src/react/src/__tests__/components/FacilityDetailsClaimedInfo.test.js
- src/react/src/components/FacilityDetailsClaimedInfo.jsx
- src/react/src/configureStore.js
- src/react/src/util/testUtils/renderWithProviders.jsx
- src/react/yarn.lock
Fix https://opensupplyhub.atlassian.net/browse/OSDEV-1027
1. Fix appearence of the Average Lead Time in facility page.
2. Update Redux Store - that will give the possibility to test smart components with predefined state easillier.
3. Add unit test for theFacilityDetailsClaimedInfo component.
> [Osdev 1027] Fix displaying of the average lead time in facility details page

- deployment/terraform/database_anonymizer_sheduled_task/docker/anonymize_script.sql
- src/anon-tools/anon.sql
- src/anon-tools/do_dump.sh
* rename speedandfuncion.com to speedandfunction.com in anonymise script
> Rename speedandfuncion.com to speedandfunction.com

- doc/release/RELEASE-PROTOCOL.md
Update code freeze date for upcoming 1.13 release.
> Update upcoming code freeze date.

- doc/release/RELEASE-PROTOCOL.md
Set responsible person for releases **v1.14** and **v.1.15**
> Update release protocol

- src/django/api/views/facility/facilities_view_set.py
- src/react/src/actions/claimFacility.js
- src/react/src/components/ClaimAttachmentsUploader.jsx
- src/react/src/components/ClaimFacilityAdditionalData.jsx
- src/react/src/components/ClaimFacilityStepper.jsx
- src/react/src/util/util.js
[OSDEV-939](https://opensupplyhub.atlassian.net/browse/OSDEV-939) **Facility Claim - UI fixes**
- Fixed Mariel UI comment -> https://opensupplyhub.atlassian.net/browse/OSDEV-939?focusedCommentId=12580
- Fix Field Validation
> [OSDEV-939] Facility Claim - UI fixes

- doc/release/RELEASE-NOTES.md
- src/django/api/management/commands/post_deployment.py
Implemented calling reindex_database command from post_deployment command.
> Call reindex_database command from post_deployment command

- doc/release/RELEASE-PROTOCOL.md
- Removed mention of autimatic test env deployment twice a week.
- Updated the day of code freeze to Tuesday.
> Update Release-Protocol file

- doc/release/RELEASE-NOTES.md
- src/django/api/mail.py
- src/django/api/templates/mail/claim_facility_submitted_body.html
- src/django/api/templates/mail/claim_facility_submitted_body.txt
- src/django/api/templates/mail/claim_facility_submitted_subject.txt
[OSDEV-1053](https://opensupplyhub.atlassian.net/browse/OSDEV-1053) - Updated email notification about the claim submission.
[OSDEV-1053]: https://opensupplyhub.atlassian.net/browse/OSDEV-1053?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [OSDEV-1053] Claims. Updating auto email responses in light of claims changes.

- src/django/api/templates/mail/claim_facility_submitted_body.html
- src/django/api/templates/mail/claim_facility_submitted_body.txt
[OSDEV-1053](https://opensupplyhub.atlassian.net/browse/OSDEV-1053) - Updated signature for the claim facility submitted letter and formatted `claim_facility_submitted_body.html`.
[OSDEV-1053]: https://opensupplyhub.atlassian.net/browse/OSDEV-1053?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [OSDEV-1053] Update signature for the claim facility submitted letter

- doc/release/RELEASE-NOTES.md
- src/django/api/reports/history_of_contributor_uploads.sql
[OSDEV-981](https://opensupplyhub.atlassian.net/browse/OSDEV-981)
Changed formula
[OSDEV-981]: https://opensupplyhub.atlassian.net/browse/OSDEV-981?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [OSDEV-981] hotfix Reporting. History of contributor uploads.

- .github/workflows/deploy_to_aws.yml
These changes let us test deploy of the database-anonymizer in the Development environment.
> Test database anonymizer in Development environment

- doc/release/RELEASE-NOTES.md
- src/react/src/components/DashboardClaimsListTable.jsx
- src/react/src/util/constants.jsx
- src/react/src/util/util.facilityClaimsXLSX.js
[OSDEV-1146](https://opensupplyhub.atlassian.net/browse/OSDEV-1146) **Facility Claim Moderation Page. Claim Decision column is not downloaded.**
- Fixed issue with missed header & data for Claim Decision column
[OSDEV-1146]: https://opensupplyhub.atlassian.net/browse/OSDEV-1146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [OSDEV-1146] Facility Claim Moderation Page. Claim Decision column is not downloaded.

- doc/release/RELEASE-PROTOCOL.md
Updated release schedule date & responsible
> Update release schedule date & responsible

- src/react/src/components/DashboardClaims.jsx
- src/react/src/components/DashboardClaimsListTable.jsx
- src/react/src/components/DashboardClaimsListTableHeader.jsx
- src/react/src/components/Filters/ClaimStatusFilter.jsx
- src/react/src/components/Filters/CountryNameFilter.jsx
Quickfix for https://opensupplyhub.atlassian.net/browse/OSDEV-1152
Disable filters while fetching facility claims.
> [OSDEV-1152] Quickfix: disable claim filter on data fetch

- doc/release/RELEASE-NOTES.md
- src/react/src/components/DashboardClaimsListTable.jsx
Quickfix for [OSDEV-1178]( https://opensupplyhub.atlassian.net/browse/OSDEV-1178)
[OSDEV-1178]: https://opensupplyhub.atlassian.net/browse/OSDEV-1178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [Osdev-1178] Getting "Something went wrong" error after clicking on Dashboard -> View Facility Claims

- doc/release/RELEASE-NOTES.md
Replace incorrect bugfix notation into relevant release section.
> Fix release notes for 1.18

- doc/release/RELEASE-NOTES.md
- src/react/src/components/DashboardClaims.jsx
Follow-up PR for [OSDEV-1178](https://opensupplyhub.atlassian.net/browse/OSDEV-1178)
[OSDEV-1178]: https://opensupplyhub.atlassian.net/browse/OSDEV-1178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [OSDEV-1178] Fix error with possible undefine claimStatuses

- .github/workflows/db_apply_anonimized.yml
Implemented clearing OpenSearch and stopping Logstash during anonymized Postgres DB restore in pre-prod/test environments to freshly populate OpenSearch with data from the restored Postgres DB.
> [OSDEV-1177] Added OpenSearch index cleaning to "DB - Apply Anonymized DB" pipeline

- .github/workflows/db_apply_anonimized.yml
- .github/workflows/deploy_to_aws.yml
- doc/release/RELEASE-NOTES.md
[[OSDEV-1177](https://opensupplyhub.atlassian.net/browse/OSDEV-1177)]
- Removed the "if" clause in the DB - Apply Anonymized DB workflow to activate the stopping of Logstash.
- Corrected grammar mistakes in the description of the job steps for stopping Logstash and clearing OpenSearch for the "DB - Apply Anonymized DB" and "Deploy to AWS" GitHub workflows.
[OSDEV-1177]: https://opensupplyhub.atlassian.net/browse/OSDEV-1177?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [OSDEV-1177] Activate stopping Logstash and correct grammar mistakes in "DB - Apply Anonymized DB" and "Deploy to AWS" GitHub workflows.

- doc/release/RELEASE-NOTES.md
- src/django/api/templates/mail/facility_list_complete_body.html
- src/django/api/templates/mail/facility_list_complete_body.txt
- src/django/api/templates/mail/facility_list_complete_subject.txt
- src/django/api/templates/mail/facility_list_rejection_body.html
- src/django/api/templates/mail/facility_list_rejection_body.txt
- src/django/api/templates/mail/facility_list_rejection_subject.txt
[OSDEV-1225)](https://opensupplyhub.atlassian.net/browse/OSDEV-1225) List upload. Updating auto email responses to improve user experience.
I updated email templates for the “Approved” or “Rejected” facility list.
> [OSDEV-1225] Update auto email response

- doc/release/RELEASE-NOTES.md
- doc/release/RELEASE-PROTOCOL.md
Set @VadimKovalenkoSNF as a person responsible for releases **1.22** and **1.23**.
Update Release Notes for release **1.22**.
> Update release notes and release protocol

- .github/workflows/deploy_to_aws.yml
- .github/workflows/release-deploy.yml
Fixed passing environment name from '[Release] Deploy' to 'Deploy to AWS' pipeline
> [OSDEV-1325] Fixed passing environment name from '[Release] Deploy' to 'Deploy to AWS' pipeline

- README.md
Fix the menu in the README and update the DB dump restore section.
> Fix the menu in the README and update the DB dump restore section.

- deployment/environments/terraform-development.tfvars
- deployment/terraform/database.tf
- deployment/terraform/variables.tf
- doc/release/RELEASE-NOTES.md
These changes will allow you to restore the database from a snapshot.
> [OSDEV-1172] Restore database from snapshot

- src/react/src/util/util.moderationEventsXLSX.js
[OSDEV-1120](https://opensupplyhub.atlassian.net/browse/OSDEV-1120) - Moderation. New Moderation Queue Page that copied from Dashboard / Facility Claims (FE). 
In this PR was correct formatting of the downloaded excel file of moderation events.
[OSDEV-1120]: https://opensupplyhub.atlassian.net/browse/OSDEV-1120?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [OSDEV-1120] Correct formatting of downloaded excel file of moderation events

- doc/release/RELEASE-NOTES.md
- src/django/api/tiler.py
Use tuple concatenation instead of converting to array.
> [OSDEV-1448] Make tile query work with multiple arguments

- doc/release/RELEASE-NOTES.md
- src/react/src/__tests__/components/DashboardModerationQueueListTable.test.js
- src/react/src/components/Dashboard/DashboardModerationQueue.jsx
- src/react/src/components/Dashboard/DashboardModerationQueueListTable.jsx
- src/react/src/reducers/DashboardModerationQueueReducer.js
- src/react/src/util/util.js
- src/react/src/util/util.moderationEventsXLSX.js
[OSDEV-1492](https://opensupplyhub.atlassian.net/browse/OSDEV-1492) Moderation. Moderation Queue Page (integration)- it is possible to send invalid date through UI
- Invalid dates are now trimmed and properly handled
- Fixed formatting timezone issue with date
[OSDEV-1492]: https://opensupplyhub.atlassian.net/browse/OSDEV-1492?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [OSDEV-1492] Moderation. Moderation Queue Page (integration)- it is possible to send invalid date through UI

- doc/release/RELEASE-PROTOCOL.md
Change the release date for version 1.27.0
> Change the release date for version 1.27.0

- src/django/api/management/commands/export_csv.py
[OSDEV-1523](https://opensupplyhub.atlassian.net/browse/OSDEV-1523) - Monthly Bulk Download
In this PR, an error related to the environment name was fixed.
[OSDEV-1523]: https://opensupplyhub.atlassian.net/browse/OSDEV-1523?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [OSDEV-1523] Fix environment name error

- src/react/src/__tests__/utils.tests.js
- src/react/src/util/util.js
Follow-up fix for [OSDEV-1365](https://opensupplyhub.atlassian.net/browse/OSDEV-1365)
[OSDEV-1365]: https://opensupplyhub.atlassian.net/browse/OSDEV-1365?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [OSDEV-1365]  (quickfix) Fix validation in utility function

- doc/release/RELEASE-PROTOCOL.md
**[Docs] Updated section QA process in doc/release/RELEASE-PROTOCOL.md**
- Made small changes in the text  for Release Testing and Smoke Testing processes
- Added links to the confluence articles with instructions for QAlity
> [Docs] Updated QA process in RELEASE-PROTOCOL.md, added instructions for test cycles in QAlity

- src/react/src/components/Contribute/ProductionLocationInfo.jsx
- src/react/src/util/constants.jsx
- src/react/src/util/styles.js
[OSDEV-1696](https://opensupplyhub.atlassian.net/browse/OSDEV-1696) Fix loader to the production location info
- Fixed the loader to be in the center as well as on the search page
[OSDEV-1696]: https://opensupplyhub.atlassian.net/browse/OSDEV-1696?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [OSDEV-1696] Fix loader to the production location info

- doc/release/RELEASE-NOTES.md
- src/react/src/__tests__/components/ProductionLocationInfo.test.js
- src/react/src/components/Contribute/ProductionLocationInfo.jsx
- src/react/src/components/ContributeForm.jsx
- src/react/src/components/StyledTooltip.jsx
- src/react/src/components/UserApiInfo.jsx
- src/react/src/util/styles.js
[OSDEV-1864](https://opensupplyhub.atlassian.net/browse/OSDEV-1864) - Releases. Block the 'Submit/Update' button on the SLC Production Location Information page during the release process.
This PR adds functionality that disables the 'Submit/Update' button on the SLC Production Location Information page when the `disable_list_uploading` feature flag is active.
[OSDEV-1864]: https://opensupplyhub.atlassian.net/browse/OSDEV-1864?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [OSDEV-1864] Block the 'Submit/Update' button on the SLC Production Location Information page during release.

- doc/release/RELEASE-PROTOCOL.md
[OSDEV-1870](https://opensupplyhub.atlassian.net/browse/OSDEV-1870) **Update release protocol**
- Assign next responsible person for releases **2.1.0** and **2.2.0**.
[OSDEV-1870]: https://opensupplyhub.atlassian.net/browse/OSDEV-1870?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [OSDEV-1870] Update release protocol

- doc/release/RELEASE-NOTES.md
- src/react/src/util/styles.js
[OSDEV-1861](https://opensupplyhub.atlassian.net/browse/OSDEV-1861) **SLC UAT Bug - Text is tiny on My Facilities Page**
- On the `My Claimed Facilities` page, the help text font size was increased to `21px`, and the margin for the `FIND MY PRODUCTION LOCATION` button was increased to `16px` to improve readability.
[OSDEV-1861]: https://opensupplyhub.atlassian.net/browse/OSDEV-1861?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [OSDEV-1861] SLC UAT Bug - Text is tiny on My Facilities Page

- doc/release/RELEASE-NOTES.md
- src/react/src/__tests__/components/ProductionLocationInfo.test.js
- src/react/src/components/Contribute/ProductionLocationInfo.jsx
[OSDEV-1842](https://opensupplyhub.atlassian.net/browse/OSDEV-1842) **SLC. In the SLC Contributions workflow, remove the pre-filled information in Additional Information.**
- Removed the pre-filled information in the `Additional Information` section of the SLC `ProductionLocationInfo` page.
- Updated UI test by new requirements
[OSDEV-1842]: https://opensupplyhub.atlassian.net/browse/OSDEV-1842?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [OSDEV-1842] SLC. In the SLC Contributions workflow, remove the pre-filled information in Additional Information.

- doc/release/RELEASE-NOTES.md
- src/react/src/components/Contribute.jsx
- src/react/src/util/constants.jsx
[OSDEV-1904](https://opensupplyhub.atlassian.net/browse/OSDEV-1904) - The step-by step instructions link on the List upload page has been updated to /resources/preparing-data.
[OSDEV-1904]: https://opensupplyhub.atlassian.net/browse/OSDEV-1904?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [OSDEV-1904] Update the instructions link on the List upload page. 

- deployment/terraform/anonymized_database_dump_scheduled_task/docker/dump.sh
- deployment/terraform/anonymized_database_dump_scheduled_task/main.tf
- doc/release/RELEASE-NOTES.md
- src/anon-tools/do_dump.sh
This pull request does not introduce any new functionality; it solely corrects typo errors in resource names
> [OSDEV-1933] Fixed typo in the cluster name

- doc/release/RELEASE-NOTES.md
- doc/release/RELEASE-PROTOCOL.md
Updated release notes for the next release, v.2.3.0, and the Release Schedule section in the release protocol.
> Update release notes for the next release v.2.3.0

- scripts/validate_ip_lists.sh
Follow-up minor fix for [OSDEV-1949](https://opensupplyhub.atlassian.net/browse/OSDEV-1949)
[OSDEV-1949]: https://opensupplyhub.atlassian.net/browse/OSDEV-1949?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [OSDEV-1949] Remove redundant ip logs release branch

- doc/release/RELEASE-NOTES.md
- src/react/src/components/Contribute.jsx
[OSDEV-1882](https://opensupplyhub.atlassian.net/browse/OSDEV-1882) SLC. "Upload multiple locations" scrolls from the bottom.
Fixed an issue where the scroll position was not resetting to the top when navigating to `Upload` page.
[OSDEV-1882]: https://opensupplyhub.atlassian.net/browse/OSDEV-1882?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [OSDEV-1882] SLC. "Upload multiple locations" scrolls from the bottom.

- deployment/terraform/vpn-ec2.tf
Backmerge fix for [OSDEV-1992](https://opensupplyhub.atlassian.net/browse/OSDEV-1992)
Setup ssh local port forwarding to VPN service.
[OSDEV-1992]: https://opensupplyhub.atlassian.net/browse/OSDEV-1992?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [OSDEV-1992][Backmerge] Setup ssh local port forwarding to VPN service

- deployment/terraform/batch.tf
- deployment/terraform/variables.tf
- doc/release/RELEASE-NOTES.md
Fixed the release notes and terraform configuration.
> [OSDEV-1951] Change the amount of desired VCPUs and fix release notes

- doc/release/RELEASE-NOTES.md
Removed empty sections for the 2.10.0 release in the RELEASE-NOTES.md file.
> Cleaned up release notes for 2.10.0

- doc/release/RELEASE-NOTES.md
- src/react/src/util/util.js
**[OSDEV-2133](https://opensupplyhub.atlassian.net/browse/OSDEV-2133) Fix CSV Parsing Issues in Self Service Upload for Lists with Special Characters**
- Implemented a fix to wrap values in double quotes to ensure correct CSV formatting for Dromo results.
[OSDEV-2133]: https://opensupplyhub.atlassian.net/browse/OSDEV-2133?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [OSDEV-2133] Fix CSV Parsing Issues in Self Service Upload for Lists with Special Characters

- .gitignore
- src/react/src/__tests__/components/DownloadFacilitiesButton.test.js
- src/react/src/actions/downloadFacilities.js
- src/react/src/components/DownloadFacilitiesButton.jsx
Follow-up fix for [OSDEV-2068](https://opensupplyhub.atlassian.net/browse/OSDEV-2068)
Fix UI issue on download tooplip with missing decrement before page reload.
[OSDEV-2068]: https://opensupplyhub.atlassian.net/browse/OSDEV-2068?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [OSDEV-2068] Fix UI issue with missing decrement before page reload
